// Code generated by MockGen. DO NOT EDIT.
// Source: ../v1/v1connect/auth.connect.go
//
// Generated by this command:
//
//	mockgen -source=../v1/v1connect/auth.connect.go -destination=./mocks/auth.connect_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	v1 "github.com/furisto/construct/api/go/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthServiceClient is a mock of AuthServiceClient interface.
type MockAuthServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceClientMockRecorder
	isgomock struct{}
}

// MockAuthServiceClientMockRecorder is the mock recorder for MockAuthServiceClient.
type MockAuthServiceClientMockRecorder struct {
	mock *MockAuthServiceClient
}

// NewMockAuthServiceClient creates a new mock instance.
func NewMockAuthServiceClient(ctrl *gomock.Controller) *MockAuthServiceClient {
	mock := &MockAuthServiceClient{ctrl: ctrl}
	mock.recorder = &MockAuthServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceClient) EXPECT() *MockAuthServiceClientMockRecorder {
	return m.recorder
}

// CreateSetupCode mocks base method.
func (m *MockAuthServiceClient) CreateSetupCode(arg0 context.Context, arg1 *connect.Request[v1.CreateSetupCodeRequest]) (*connect.Response[v1.CreateSetupCodeResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSetupCode", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateSetupCodeResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSetupCode indicates an expected call of CreateSetupCode.
func (mr *MockAuthServiceClientMockRecorder) CreateSetupCode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSetupCode", reflect.TypeOf((*MockAuthServiceClient)(nil).CreateSetupCode), arg0, arg1)
}

// CreateToken mocks base method.
func (m *MockAuthServiceClient) CreateToken(arg0 context.Context, arg1 *connect.Request[v1.CreateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateTokenResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockAuthServiceClientMockRecorder) CreateToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockAuthServiceClient)(nil).CreateToken), arg0, arg1)
}

// ExchangeSetupCode mocks base method.
func (m *MockAuthServiceClient) ExchangeSetupCode(arg0 context.Context, arg1 *connect.Request[v1.ExchangeSetupCodeRequest]) (*connect.Response[v1.ExchangeSetupCodeResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeSetupCode", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ExchangeSetupCodeResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeSetupCode indicates an expected call of ExchangeSetupCode.
func (mr *MockAuthServiceClientMockRecorder) ExchangeSetupCode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeSetupCode", reflect.TypeOf((*MockAuthServiceClient)(nil).ExchangeSetupCode), arg0, arg1)
}

// ListTokens mocks base method.
func (m *MockAuthServiceClient) ListTokens(arg0 context.Context, arg1 *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTokens", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListTokensResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTokens indicates an expected call of ListTokens.
func (mr *MockAuthServiceClientMockRecorder) ListTokens(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTokens", reflect.TypeOf((*MockAuthServiceClient)(nil).ListTokens), arg0, arg1)
}

// RevokeToken mocks base method.
func (m *MockAuthServiceClient) RevokeToken(arg0 context.Context, arg1 *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.RevokeTokenResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockAuthServiceClientMockRecorder) RevokeToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockAuthServiceClient)(nil).RevokeToken), arg0, arg1)
}

// MockAuthServiceHandler is a mock of AuthServiceHandler interface.
type MockAuthServiceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceHandlerMockRecorder
	isgomock struct{}
}

// MockAuthServiceHandlerMockRecorder is the mock recorder for MockAuthServiceHandler.
type MockAuthServiceHandlerMockRecorder struct {
	mock *MockAuthServiceHandler
}

// NewMockAuthServiceHandler creates a new mock instance.
func NewMockAuthServiceHandler(ctrl *gomock.Controller) *MockAuthServiceHandler {
	mock := &MockAuthServiceHandler{ctrl: ctrl}
	mock.recorder = &MockAuthServiceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceHandler) EXPECT() *MockAuthServiceHandlerMockRecorder {
	return m.recorder
}

// CreateSetupCode mocks base method.
func (m *MockAuthServiceHandler) CreateSetupCode(arg0 context.Context, arg1 *connect.Request[v1.CreateSetupCodeRequest]) (*connect.Response[v1.CreateSetupCodeResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSetupCode", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateSetupCodeResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSetupCode indicates an expected call of CreateSetupCode.
func (mr *MockAuthServiceHandlerMockRecorder) CreateSetupCode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSetupCode", reflect.TypeOf((*MockAuthServiceHandler)(nil).CreateSetupCode), arg0, arg1)
}

// CreateToken mocks base method.
func (m *MockAuthServiceHandler) CreateToken(arg0 context.Context, arg1 *connect.Request[v1.CreateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateTokenResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockAuthServiceHandlerMockRecorder) CreateToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockAuthServiceHandler)(nil).CreateToken), arg0, arg1)
}

// ExchangeSetupCode mocks base method.
func (m *MockAuthServiceHandler) ExchangeSetupCode(arg0 context.Context, arg1 *connect.Request[v1.ExchangeSetupCodeRequest]) (*connect.Response[v1.ExchangeSetupCodeResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeSetupCode", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ExchangeSetupCodeResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeSetupCode indicates an expected call of ExchangeSetupCode.
func (mr *MockAuthServiceHandlerMockRecorder) ExchangeSetupCode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeSetupCode", reflect.TypeOf((*MockAuthServiceHandler)(nil).ExchangeSetupCode), arg0, arg1)
}

// ListTokens mocks base method.
func (m *MockAuthServiceHandler) ListTokens(arg0 context.Context, arg1 *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTokens", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListTokensResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTokens indicates an expected call of ListTokens.
func (mr *MockAuthServiceHandlerMockRecorder) ListTokens(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTokens", reflect.TypeOf((*MockAuthServiceHandler)(nil).ListTokens), arg0, arg1)
}

// RevokeToken mocks base method.
func (m *MockAuthServiceHandler) RevokeToken(arg0 context.Context, arg1 *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.RevokeTokenResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockAuthServiceHandlerMockRecorder) RevokeToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockAuthServiceHandler)(nil).RevokeToken), arg0, arg1)
}
