// Code generated by MockGen. DO NOT EDIT.
// Source: ../v1/v1connect/event.connect.go
//
// Generated by this command:
//
//	mockgen -source=../v1/v1connect/event.connect.go -destination=./mocks/event.connect_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	v1 "github.com/furisto/construct/api/go/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockEventServiceClient is a mock of EventServiceClient interface.
type MockEventServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockEventServiceClientMockRecorder
	isgomock struct{}
}

// MockEventServiceClientMockRecorder is the mock recorder for MockEventServiceClient.
type MockEventServiceClientMockRecorder struct {
	mock *MockEventServiceClient
}

// NewMockEventServiceClient creates a new mock instance.
func NewMockEventServiceClient(ctrl *gomock.Controller) *MockEventServiceClient {
	mock := &MockEventServiceClient{ctrl: ctrl}
	mock.recorder = &MockEventServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventServiceClient) EXPECT() *MockEventServiceClientMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *MockEventServiceClient) Subscribe(arg0 context.Context, arg1 *connect.Request[v1.EventSubscribeRequest]) (*connect.ServerStreamForClient[v1.EventSubscribeResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0, arg1)
	ret0, _ := ret[0].(*connect.ServerStreamForClient[v1.EventSubscribeResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockEventServiceClientMockRecorder) Subscribe(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockEventServiceClient)(nil).Subscribe), arg0, arg1)
}

// MockEventServiceHandler is a mock of EventServiceHandler interface.
type MockEventServiceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockEventServiceHandlerMockRecorder
	isgomock struct{}
}

// MockEventServiceHandlerMockRecorder is the mock recorder for MockEventServiceHandler.
type MockEventServiceHandlerMockRecorder struct {
	mock *MockEventServiceHandler
}

// NewMockEventServiceHandler creates a new mock instance.
func NewMockEventServiceHandler(ctrl *gomock.Controller) *MockEventServiceHandler {
	mock := &MockEventServiceHandler{ctrl: ctrl}
	mock.recorder = &MockEventServiceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventServiceHandler) EXPECT() *MockEventServiceHandlerMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *MockEventServiceHandler) Subscribe(arg0 context.Context, arg1 *connect.Request[v1.EventSubscribeRequest], arg2 *connect.ServerStream[v1.EventSubscribeResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockEventServiceHandlerMockRecorder) Subscribe(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockEventServiceHandler)(nil).Subscribe), arg0, arg1, arg2)
}
