// Code generated by MockGen. DO NOT EDIT.
// Source: ./v1/v1connect/skill.connect.go
//
// Generated by this command:
//
//	mockgen -source=./v1/v1connect/skill.connect.go -destination=./client/mocks/skill.connect_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	v1 "github.com/furisto/construct/api/go/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockSkillServiceClient is a mock of SkillServiceClient interface.
type MockSkillServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockSkillServiceClientMockRecorder
	isgomock struct{}
}

// MockSkillServiceClientMockRecorder is the mock recorder for MockSkillServiceClient.
type MockSkillServiceClientMockRecorder struct {
	mock *MockSkillServiceClient
}

// NewMockSkillServiceClient creates a new mock instance.
func NewMockSkillServiceClient(ctrl *gomock.Controller) *MockSkillServiceClient {
	mock := &MockSkillServiceClient{ctrl: ctrl}
	mock.recorder = &MockSkillServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillServiceClient) EXPECT() *MockSkillServiceClientMockRecorder {
	return m.recorder
}

// DeleteSkill mocks base method.
func (m *MockSkillServiceClient) DeleteSkill(arg0 context.Context, arg1 *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSkill", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteSkillResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSkill indicates an expected call of DeleteSkill.
func (mr *MockSkillServiceClientMockRecorder) DeleteSkill(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSkill", reflect.TypeOf((*MockSkillServiceClient)(nil).DeleteSkill), arg0, arg1)
}

// InstallSkill mocks base method.
func (m *MockSkillServiceClient) InstallSkill(arg0 context.Context, arg1 *connect.Request[v1.InstallSkillRequest]) (*connect.Response[v1.InstallSkillResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallSkill", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.InstallSkillResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstallSkill indicates an expected call of InstallSkill.
func (mr *MockSkillServiceClientMockRecorder) InstallSkill(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallSkill", reflect.TypeOf((*MockSkillServiceClient)(nil).InstallSkill), arg0, arg1)
}

// ListSkills mocks base method.
func (m *MockSkillServiceClient) ListSkills(arg0 context.Context, arg1 *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSkills", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListSkillsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSkills indicates an expected call of ListSkills.
func (mr *MockSkillServiceClientMockRecorder) ListSkills(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSkills", reflect.TypeOf((*MockSkillServiceClient)(nil).ListSkills), arg0, arg1)
}

// UpdateSkill mocks base method.
func (m *MockSkillServiceClient) UpdateSkill(arg0 context.Context, arg1 *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSkill", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateSkillResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSkill indicates an expected call of UpdateSkill.
func (mr *MockSkillServiceClientMockRecorder) UpdateSkill(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSkill", reflect.TypeOf((*MockSkillServiceClient)(nil).UpdateSkill), arg0, arg1)
}

// MockSkillServiceHandler is a mock of SkillServiceHandler interface.
type MockSkillServiceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockSkillServiceHandlerMockRecorder
	isgomock struct{}
}

// MockSkillServiceHandlerMockRecorder is the mock recorder for MockSkillServiceHandler.
type MockSkillServiceHandlerMockRecorder struct {
	mock *MockSkillServiceHandler
}

// NewMockSkillServiceHandler creates a new mock instance.
func NewMockSkillServiceHandler(ctrl *gomock.Controller) *MockSkillServiceHandler {
	mock := &MockSkillServiceHandler{ctrl: ctrl}
	mock.recorder = &MockSkillServiceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillServiceHandler) EXPECT() *MockSkillServiceHandlerMockRecorder {
	return m.recorder
}

// DeleteSkill mocks base method.
func (m *MockSkillServiceHandler) DeleteSkill(arg0 context.Context, arg1 *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSkill", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteSkillResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSkill indicates an expected call of DeleteSkill.
func (mr *MockSkillServiceHandlerMockRecorder) DeleteSkill(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSkill", reflect.TypeOf((*MockSkillServiceHandler)(nil).DeleteSkill), arg0, arg1)
}

// InstallSkill mocks base method.
func (m *MockSkillServiceHandler) InstallSkill(arg0 context.Context, arg1 *connect.Request[v1.InstallSkillRequest]) (*connect.Response[v1.InstallSkillResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallSkill", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.InstallSkillResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstallSkill indicates an expected call of InstallSkill.
func (mr *MockSkillServiceHandlerMockRecorder) InstallSkill(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallSkill", reflect.TypeOf((*MockSkillServiceHandler)(nil).InstallSkill), arg0, arg1)
}

// ListSkills mocks base method.
func (m *MockSkillServiceHandler) ListSkills(arg0 context.Context, arg1 *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSkills", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListSkillsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSkills indicates an expected call of ListSkills.
func (mr *MockSkillServiceHandlerMockRecorder) ListSkills(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSkills", reflect.TypeOf((*MockSkillServiceHandler)(nil).ListSkills), arg0, arg1)
}

// UpdateSkill mocks base method.
func (m *MockSkillServiceHandler) UpdateSkill(arg0 context.Context, arg1 *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSkill", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateSkillResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSkill indicates an expected call of UpdateSkill.
func (mr *MockSkillServiceHandlerMockRecorder) UpdateSkill(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSkill", reflect.TypeOf((*MockSkillServiceHandler)(nil).UpdateSkill), arg0, arg1)
}
