// Code generated by ent. DO NOT EDIT.

package modelprovider

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/furisto/construct/backend/memory/predicate"
	"github.com/furisto/construct/backend/memory/schema/types"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldUpdateTime, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldName, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldURL, v))
}

// SecretRef applies equality check predicate on the "secret_ref" field. It's identical to SecretRefEQ.
func SecretRef(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldSecretRef, v))
}

// SecretStore applies equality check predicate on the "secret_store" field. It's identical to SecretStoreEQ.
func SecretStore(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldSecretStore, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldEnabled, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLTE(FieldUpdateTime, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldContainsFold(FieldName, v))
}

// ProviderTypeEQ applies the EQ predicate on the "provider_type" field.
func ProviderTypeEQ(v types.ModelProviderType) predicate.ModelProvider {
	vc := v
	return predicate.ModelProvider(sql.FieldEQ(FieldProviderType, vc))
}

// ProviderTypeNEQ applies the NEQ predicate on the "provider_type" field.
func ProviderTypeNEQ(v types.ModelProviderType) predicate.ModelProvider {
	vc := v
	return predicate.ModelProvider(sql.FieldNEQ(FieldProviderType, vc))
}

// ProviderTypeIn applies the In predicate on the "provider_type" field.
func ProviderTypeIn(vs ...types.ModelProviderType) predicate.ModelProvider {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ModelProvider(sql.FieldIn(FieldProviderType, v...))
}

// ProviderTypeNotIn applies the NotIn predicate on the "provider_type" field.
func ProviderTypeNotIn(vs ...types.ModelProviderType) predicate.ModelProvider {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ModelProvider(sql.FieldNotIn(FieldProviderType, v...))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldContainsFold(FieldURL, v))
}

// SecretRefEQ applies the EQ predicate on the "secret_ref" field.
func SecretRefEQ(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldSecretRef, v))
}

// SecretRefNEQ applies the NEQ predicate on the "secret_ref" field.
func SecretRefNEQ(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNEQ(FieldSecretRef, v))
}

// SecretRefIn applies the In predicate on the "secret_ref" field.
func SecretRefIn(vs ...string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldIn(FieldSecretRef, vs...))
}

// SecretRefNotIn applies the NotIn predicate on the "secret_ref" field.
func SecretRefNotIn(vs ...string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNotIn(FieldSecretRef, vs...))
}

// SecretRefGT applies the GT predicate on the "secret_ref" field.
func SecretRefGT(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGT(FieldSecretRef, v))
}

// SecretRefGTE applies the GTE predicate on the "secret_ref" field.
func SecretRefGTE(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGTE(FieldSecretRef, v))
}

// SecretRefLT applies the LT predicate on the "secret_ref" field.
func SecretRefLT(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLT(FieldSecretRef, v))
}

// SecretRefLTE applies the LTE predicate on the "secret_ref" field.
func SecretRefLTE(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLTE(FieldSecretRef, v))
}

// SecretRefContains applies the Contains predicate on the "secret_ref" field.
func SecretRefContains(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldContains(FieldSecretRef, v))
}

// SecretRefHasPrefix applies the HasPrefix predicate on the "secret_ref" field.
func SecretRefHasPrefix(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldHasPrefix(FieldSecretRef, v))
}

// SecretRefHasSuffix applies the HasSuffix predicate on the "secret_ref" field.
func SecretRefHasSuffix(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldHasSuffix(FieldSecretRef, v))
}

// SecretRefEqualFold applies the EqualFold predicate on the "secret_ref" field.
func SecretRefEqualFold(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEqualFold(FieldSecretRef, v))
}

// SecretRefContainsFold applies the ContainsFold predicate on the "secret_ref" field.
func SecretRefContainsFold(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldContainsFold(FieldSecretRef, v))
}

// SecretStoreEQ applies the EQ predicate on the "secret_store" field.
func SecretStoreEQ(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldSecretStore, v))
}

// SecretStoreNEQ applies the NEQ predicate on the "secret_store" field.
func SecretStoreNEQ(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNEQ(FieldSecretStore, v))
}

// SecretStoreIn applies the In predicate on the "secret_store" field.
func SecretStoreIn(vs ...string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldIn(FieldSecretStore, vs...))
}

// SecretStoreNotIn applies the NotIn predicate on the "secret_store" field.
func SecretStoreNotIn(vs ...string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNotIn(FieldSecretStore, vs...))
}

// SecretStoreGT applies the GT predicate on the "secret_store" field.
func SecretStoreGT(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGT(FieldSecretStore, v))
}

// SecretStoreGTE applies the GTE predicate on the "secret_store" field.
func SecretStoreGTE(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldGTE(FieldSecretStore, v))
}

// SecretStoreLT applies the LT predicate on the "secret_store" field.
func SecretStoreLT(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLT(FieldSecretStore, v))
}

// SecretStoreLTE applies the LTE predicate on the "secret_store" field.
func SecretStoreLTE(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldLTE(FieldSecretStore, v))
}

// SecretStoreContains applies the Contains predicate on the "secret_store" field.
func SecretStoreContains(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldContains(FieldSecretStore, v))
}

// SecretStoreHasPrefix applies the HasPrefix predicate on the "secret_store" field.
func SecretStoreHasPrefix(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldHasPrefix(FieldSecretStore, v))
}

// SecretStoreHasSuffix applies the HasSuffix predicate on the "secret_store" field.
func SecretStoreHasSuffix(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldHasSuffix(FieldSecretStore, v))
}

// SecretStoreEqualFold applies the EqualFold predicate on the "secret_store" field.
func SecretStoreEqualFold(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEqualFold(FieldSecretStore, v))
}

// SecretStoreContainsFold applies the ContainsFold predicate on the "secret_store" field.
func SecretStoreContainsFold(v string) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldContainsFold(FieldSecretStore, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ModelProvider {
	return predicate.ModelProvider(sql.FieldNEQ(FieldEnabled, v))
}

// HasModels applies the HasEdge predicate on the "models" edge.
func HasModels() predicate.ModelProvider {
	return predicate.ModelProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ModelsTable, ModelsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasModelsWith applies the HasEdge predicate on the "models" edge with a given conditions (other predicates).
func HasModelsWith(preds ...predicate.Model) predicate.ModelProvider {
	return predicate.ModelProvider(func(s *sql.Selector) {
		step := newModelsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelProvider) predicate.ModelProvider {
	return predicate.ModelProvider(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelProvider) predicate.ModelProvider {
	return predicate.ModelProvider(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelProvider) predicate.ModelProvider {
	return predicate.ModelProvider(sql.NotPredicates(p))
}
