// Code generated by ent. DO NOT EDIT.

package tasksummary

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/furisto/construct/backend/memory/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldEQ(FieldUpdateTime, v))
}

// MessageAnchor applies equality check predicate on the "message_anchor" field. It's identical to MessageAnchorEQ.
func MessageAnchor(v uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldEQ(FieldMessageAnchor, v))
}

// TokenBudget applies equality check predicate on the "token_budget" field. It's identical to TokenBudgetEQ.
func TokenBudget(v int64) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldEQ(FieldTokenBudget, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldEQ(FieldTaskID, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldLTE(FieldUpdateTime, v))
}

// MessageAnchorEQ applies the EQ predicate on the "message_anchor" field.
func MessageAnchorEQ(v uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldEQ(FieldMessageAnchor, v))
}

// MessageAnchorNEQ applies the NEQ predicate on the "message_anchor" field.
func MessageAnchorNEQ(v uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldNEQ(FieldMessageAnchor, v))
}

// MessageAnchorIn applies the In predicate on the "message_anchor" field.
func MessageAnchorIn(vs ...uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldIn(FieldMessageAnchor, vs...))
}

// MessageAnchorNotIn applies the NotIn predicate on the "message_anchor" field.
func MessageAnchorNotIn(vs ...uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldNotIn(FieldMessageAnchor, vs...))
}

// TokenBudgetEQ applies the EQ predicate on the "token_budget" field.
func TokenBudgetEQ(v int64) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldEQ(FieldTokenBudget, v))
}

// TokenBudgetNEQ applies the NEQ predicate on the "token_budget" field.
func TokenBudgetNEQ(v int64) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldNEQ(FieldTokenBudget, v))
}

// TokenBudgetIn applies the In predicate on the "token_budget" field.
func TokenBudgetIn(vs ...int64) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldIn(FieldTokenBudget, vs...))
}

// TokenBudgetNotIn applies the NotIn predicate on the "token_budget" field.
func TokenBudgetNotIn(vs ...int64) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldNotIn(FieldTokenBudget, vs...))
}

// TokenBudgetGT applies the GT predicate on the "token_budget" field.
func TokenBudgetGT(v int64) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldGT(FieldTokenBudget, v))
}

// TokenBudgetGTE applies the GTE predicate on the "token_budget" field.
func TokenBudgetGTE(v int64) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldGTE(FieldTokenBudget, v))
}

// TokenBudgetLT applies the LT predicate on the "token_budget" field.
func TokenBudgetLT(v int64) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldLT(FieldTokenBudget, v))
}

// TokenBudgetLTE applies the LTE predicate on the "token_budget" field.
func TokenBudgetLTE(v int64) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldLTE(FieldTokenBudget, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...uuid.UUID) predicate.TaskSummary {
	return predicate.TaskSummary(sql.FieldNotIn(FieldTaskID, vs...))
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.TaskSummary {
	return predicate.TaskSummary(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.TaskSummary {
	return predicate.TaskSummary(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMessage applies the HasEdge predicate on the "message" edge.
func HasMessage() predicate.TaskSummary {
	return predicate.TaskSummary(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, MessageTable, MessageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessageWith applies the HasEdge predicate on the "message" edge with a given conditions (other predicates).
func HasMessageWith(preds ...predicate.Message) predicate.TaskSummary {
	return predicate.TaskSummary(func(s *sql.Selector) {
		step := newMessageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TaskSummary) predicate.TaskSummary {
	return predicate.TaskSummary(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TaskSummary) predicate.TaskSummary {
	return predicate.TaskSummary(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TaskSummary) predicate.TaskSummary {
	return predicate.TaskSummary(sql.NotPredicates(p))
}
