// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: construct/v1/auth.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateTokenRequest contains parameters for creating a new token.
type CreateTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable name for the token. Must be unique.
	// Used for identification in listings and revocation.
	// Example: "macbook-thomas", "ci-pipeline"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// How long until the token expires. Default: 90 days.
	// Maximum allowed value is 365 days.
	ExpiresIn *durationpb.Duration `protobuf:"bytes,2,opt,name=expires_in,json=expiresIn,proto3,oneof" json:"expires_in,omitempty"`
	// Optional description for the token's intended use.
	Description   *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	mi := &file_construct_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTokenRequest) GetExpiresIn() *durationpb.Duration {
	if x != nil {
		return x.ExpiresIn
	}
	return nil
}

func (x *CreateTokenRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// CreateTokenResponse contains the newly created token.
type CreateTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plaintext token value. This is the only time this value is available;
	// it is not stored and cannot be retrieved again.
	//
	// Format: "ct_<base64url-encoded-random-bytes>"
	// The "ct_" prefix identifies Construct tokens in logs and configurations.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// When the token will expire.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenResponse) Reset() {
	*x = CreateTokenResponse{}
	mi := &file_construct_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenResponse) ProtoMessage() {}

func (x *CreateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateTokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// CreateSetupCodeRequest contains parameters for creating a setup code.
type CreateSetupCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name for the token that will be created when the code is exchanged.
	// Must be unique at the time of exchange.
	TokenName string `protobuf:"bytes,1,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	// How long until the setup code expires. Default: 5 minutes.
	// Maximum allowed value is 3 days.
	ExpiresIn *durationpb.Duration `protobuf:"bytes,2,opt,name=expires_in,json=expiresIn,proto3,oneof" json:"expires_in,omitempty"`
	// How long the resulting token should be valid. Default: 90 days.
	TokenExpiresIn *durationpb.Duration `protobuf:"bytes,3,opt,name=token_expires_in,json=tokenExpiresIn,proto3,oneof" json:"token_expires_in,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSetupCodeRequest) Reset() {
	*x = CreateSetupCodeRequest{}
	mi := &file_construct_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSetupCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSetupCodeRequest) ProtoMessage() {}

func (x *CreateSetupCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSetupCodeRequest.ProtoReflect.Descriptor instead.
func (*CreateSetupCodeRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSetupCodeRequest) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *CreateSetupCodeRequest) GetExpiresIn() *durationpb.Duration {
	if x != nil {
		return x.ExpiresIn
	}
	return nil
}

func (x *CreateSetupCodeRequest) GetTokenExpiresIn() *durationpb.Duration {
	if x != nil {
		return x.TokenExpiresIn
	}
	return nil
}

// CreateSetupCodeResponse contains the generated setup code.
type CreateSetupCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Short, human-readable setup code. Format: "XXXX-XXXX"
	SetupCode string `protobuf:"bytes,1,opt,name=setup_code,json=setupCode,proto3" json:"setup_code,omitempty"`
	// When the setup code expires (typically 15 minutes).
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSetupCodeResponse) Reset() {
	*x = CreateSetupCodeResponse{}
	mi := &file_construct_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSetupCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSetupCodeResponse) ProtoMessage() {}

func (x *CreateSetupCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSetupCodeResponse.ProtoReflect.Descriptor instead.
func (*CreateSetupCodeResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSetupCodeResponse) GetSetupCode() string {
	if x != nil {
		return x.SetupCode
	}
	return ""
}

func (x *CreateSetupCodeResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// ListTokensRequest contains optional filters for listing tokens.
type ListTokensRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by name prefix.
	NamePrefix string `protobuf:"bytes,1,opt,name=name_prefix,json=namePrefix,proto3" json:"name_prefix,omitempty"`
	// Optional: include expired tokens in results. Default: false.
	IncludeExpired bool `protobuf:"varint,2,opt,name=include_expired,json=includeExpired,proto3" json:"include_expired,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTokensRequest) Reset() {
	*x = ListTokensRequest{}
	mi := &file_construct_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensRequest) ProtoMessage() {}

func (x *ListTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensRequest.ProtoReflect.Descriptor instead.
func (*ListTokensRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ListTokensRequest) GetNamePrefix() string {
	if x != nil {
		return x.NamePrefix
	}
	return ""
}

func (x *ListTokensRequest) GetIncludeExpired() bool {
	if x != nil {
		return x.IncludeExpired
	}
	return false
}

// ListTokensResponse contains token metadata.
type ListTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*TokenInfo           `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensResponse) Reset() {
	*x = ListTokensResponse{}
	mi := &file_construct_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensResponse) ProtoMessage() {}

func (x *ListTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensResponse.ProtoReflect.Descriptor instead.
func (*ListTokensResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ListTokensResponse) GetTokens() []*TokenInfo {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// TokenInfo contains metadata about a token
type TokenInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the token.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Optional description.
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// When the token was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the token expires.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Whether the token is currently valid (not expired, not revoked).
	IsActive      bool `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_construct_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_construct_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *TokenInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TokenInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenInfo) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *TokenInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TokenInfo) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *TokenInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// RevokeTokenRequest identifies the token to revoke.
type RevokeTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the token to revoke.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_construct_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RevokeTokenResponse confirms the revocation.
type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_construct_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_auth_proto_rawDescGZIP(), []int{8}
}

// ExchangeSetupCodeRequest contains the setup code to exchange.
type ExchangeSetupCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Format: "XXXX-XXXX"
	SetupCode     string `protobuf:"bytes,1,opt,name=setup_code,json=setupCode,proto3" json:"setup_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeSetupCodeRequest) Reset() {
	*x = ExchangeSetupCodeRequest{}
	mi := &file_construct_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeSetupCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeSetupCodeRequest) ProtoMessage() {}

func (x *ExchangeSetupCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeSetupCodeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeSetupCodeRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ExchangeSetupCodeRequest) GetSetupCode() string {
	if x != nil {
		return x.SetupCode
	}
	return ""
}

// ExchangeSetupCodeResponse contains the token issued in exchange.
type ExchangeSetupCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plaintext token value.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// When the token expires.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// The token name (as specified when the setup code was created).
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeSetupCodeResponse) Reset() {
	*x = ExchangeSetupCodeResponse{}
	mi := &file_construct_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeSetupCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeSetupCodeResponse) ProtoMessage() {}

func (x *ExchangeSetupCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeSetupCodeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeSetupCodeResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ExchangeSetupCodeResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ExchangeSetupCodeResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ExchangeSetupCodeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_construct_v1_auth_proto protoreflect.FileDescriptor

const file_construct_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x17construct/v1/auth.proto\x12\fconstruct.v1\x1a\x1bbuf/validate/validate.proto\x1a\x19construct/v1/common.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x01\n" +
	"\x12CreateTokenRequest\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12=\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\v2\x19.google.protobuf.DurationH\x00R\texpiresIn\x88\x01\x01\x12/\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10H\x01R\vdescription\x88\x01\x01B\r\n" +
	"\v_expires_inB\x0e\n" +
	"\f_description\"z\n" +
	"\x13CreateTokenResponse\x12 \n" +
	"\x05token\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x05token\x12A\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\texpiresAt\"\xf0\x01\n" +
	"\x16CreateSetupCodeRequest\x12)\n" +
	"\n" +
	"token_name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\ttokenName\x12=\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\v2\x19.google.protobuf.DurationH\x00R\texpiresIn\x88\x01\x01\x12H\n" +
	"\x10token_expires_in\x18\x03 \x01(\v2\x19.google.protobuf.DurationH\x01R\x0etokenExpiresIn\x88\x01\x01B\r\n" +
	"\v_expires_inB\x13\n" +
	"\x11_token_expires_in\"\xa1\x01\n" +
	"\x17CreateSetupCodeResponse\x12C\n" +
	"\n" +
	"setup_code\x18\x01 \x01(\tB$\xbaH!r\x1f\x10\x01\x18\t2\x19^[A-Z0-9]{4}-[A-Z0-9]{4}$R\tsetupCode\x12A\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\texpiresAt\"]\n" +
	"\x11ListTokensRequest\x12\x1f\n" +
	"\vname_prefix\x18\x01 \x01(\tR\n" +
	"namePrefix\x12'\n" +
	"\x0finclude_expired\x18\x02 \x01(\bR\x0eincludeExpired\"E\n" +
	"\x12ListTokensResponse\x12/\n" +
	"\x06tokens\x18\x01 \x03(\v2\x17.construct.v1.TokenInfoR\x06tokens\"\xb1\x02\n" +
	"\tTokenInfo\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12/\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10H\x00R\vdescription\x88\x01\x01\x12A\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tcreatedAt\x12A\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\texpiresAt\x12#\n" +
	"\tis_active\x18\a \x01(\bB\x06\xbaH\x03\xc8\x01\x01R\bisActiveB\x0e\n" +
	"\f_description\".\n" +
	"\x12RevokeTokenRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"\x15\n" +
	"\x13RevokeTokenResponse\"_\n" +
	"\x18ExchangeSetupCodeRequest\x12C\n" +
	"\n" +
	"setup_code\x18\x01 \x01(\tB$\xbaH!r\x1f\x10\x01\x18\t2\x19^[A-Z0-9]{4}-[A-Z0-9]{4}$R\tsetupCode\"\xa0\x01\n" +
	"\x19ExchangeSetupCodeResponse\x12 \n" +
	"\x05token\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x05token\x12A\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\texpiresAt\x12\x1e\n" +
	"\x04name\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name2\xcc\x03\n" +
	"\vAuthService\x12R\n" +
	"\vCreateToken\x12 .construct.v1.CreateTokenRequest\x1a!.construct.v1.CreateTokenResponse\x12^\n" +
	"\x0fCreateSetupCode\x12$.construct.v1.CreateSetupCodeRequest\x1a%.construct.v1.CreateSetupCodeResponse\x12O\n" +
	"\n" +
	"ListTokens\x12\x1f.construct.v1.ListTokensRequest\x1a .construct.v1.ListTokensResponse\x12R\n" +
	"\vRevokeToken\x12 .construct.v1.RevokeTokenRequest\x1a!.construct.v1.RevokeTokenResponse\x12d\n" +
	"\x11ExchangeSetupCode\x12&.construct.v1.ExchangeSetupCodeRequest\x1a'.construct.v1.ExchangeSetupCodeResponseB(Z&github.com/furisto/construct/api/go/v1b\x06proto3"

var (
	file_construct_v1_auth_proto_rawDescOnce sync.Once
	file_construct_v1_auth_proto_rawDescData []byte
)

func file_construct_v1_auth_proto_rawDescGZIP() []byte {
	file_construct_v1_auth_proto_rawDescOnce.Do(func() {
		file_construct_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_construct_v1_auth_proto_rawDesc), len(file_construct_v1_auth_proto_rawDesc)))
	})
	return file_construct_v1_auth_proto_rawDescData
}

var file_construct_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_construct_v1_auth_proto_goTypes = []any{
	(*CreateTokenRequest)(nil),        // 0: construct.v1.CreateTokenRequest
	(*CreateTokenResponse)(nil),       // 1: construct.v1.CreateTokenResponse
	(*CreateSetupCodeRequest)(nil),    // 2: construct.v1.CreateSetupCodeRequest
	(*CreateSetupCodeResponse)(nil),   // 3: construct.v1.CreateSetupCodeResponse
	(*ListTokensRequest)(nil),         // 4: construct.v1.ListTokensRequest
	(*ListTokensResponse)(nil),        // 5: construct.v1.ListTokensResponse
	(*TokenInfo)(nil),                 // 6: construct.v1.TokenInfo
	(*RevokeTokenRequest)(nil),        // 7: construct.v1.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),       // 8: construct.v1.RevokeTokenResponse
	(*ExchangeSetupCodeRequest)(nil),  // 9: construct.v1.ExchangeSetupCodeRequest
	(*ExchangeSetupCodeResponse)(nil), // 10: construct.v1.ExchangeSetupCodeResponse
	(*durationpb.Duration)(nil),       // 11: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
}
var file_construct_v1_auth_proto_depIdxs = []int32{
	11, // 0: construct.v1.CreateTokenRequest.expires_in:type_name -> google.protobuf.Duration
	12, // 1: construct.v1.CreateTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	11, // 2: construct.v1.CreateSetupCodeRequest.expires_in:type_name -> google.protobuf.Duration
	11, // 3: construct.v1.CreateSetupCodeRequest.token_expires_in:type_name -> google.protobuf.Duration
	12, // 4: construct.v1.CreateSetupCodeResponse.expires_at:type_name -> google.protobuf.Timestamp
	6,  // 5: construct.v1.ListTokensResponse.tokens:type_name -> construct.v1.TokenInfo
	12, // 6: construct.v1.TokenInfo.created_at:type_name -> google.protobuf.Timestamp
	12, // 7: construct.v1.TokenInfo.expires_at:type_name -> google.protobuf.Timestamp
	12, // 8: construct.v1.ExchangeSetupCodeResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 9: construct.v1.AuthService.CreateToken:input_type -> construct.v1.CreateTokenRequest
	2,  // 10: construct.v1.AuthService.CreateSetupCode:input_type -> construct.v1.CreateSetupCodeRequest
	4,  // 11: construct.v1.AuthService.ListTokens:input_type -> construct.v1.ListTokensRequest
	7,  // 12: construct.v1.AuthService.RevokeToken:input_type -> construct.v1.RevokeTokenRequest
	9,  // 13: construct.v1.AuthService.ExchangeSetupCode:input_type -> construct.v1.ExchangeSetupCodeRequest
	1,  // 14: construct.v1.AuthService.CreateToken:output_type -> construct.v1.CreateTokenResponse
	3,  // 15: construct.v1.AuthService.CreateSetupCode:output_type -> construct.v1.CreateSetupCodeResponse
	5,  // 16: construct.v1.AuthService.ListTokens:output_type -> construct.v1.ListTokensResponse
	8,  // 17: construct.v1.AuthService.RevokeToken:output_type -> construct.v1.RevokeTokenResponse
	10, // 18: construct.v1.AuthService.ExchangeSetupCode:output_type -> construct.v1.ExchangeSetupCodeResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_construct_v1_auth_proto_init() }
func file_construct_v1_auth_proto_init() {
	if File_construct_v1_auth_proto != nil {
		return
	}
	file_construct_v1_common_proto_init()
	file_construct_v1_auth_proto_msgTypes[0].OneofWrappers = []any{}
	file_construct_v1_auth_proto_msgTypes[2].OneofWrappers = []any{}
	file_construct_v1_auth_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_construct_v1_auth_proto_rawDesc), len(file_construct_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_construct_v1_auth_proto_goTypes,
		DependencyIndexes: file_construct_v1_auth_proto_depIdxs,
		MessageInfos:      file_construct_v1_auth_proto_msgTypes,
	}.Build()
	File_construct_v1_auth_proto = out.File
	file_construct_v1_auth_proto_goTypes = nil
	file_construct_v1_auth_proto_depIdxs = nil
}
