// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: construct/v1/message.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageRole int32

const (
	MessageRole_MESSAGE_ROLE_UNSPECIFIED MessageRole = 0
	MessageRole_MESSAGE_ROLE_USER        MessageRole = 1
	MessageRole_MESSAGE_ROLE_ASSISTANT   MessageRole = 2
)

// Enum value maps for MessageRole.
var (
	MessageRole_name = map[int32]string{
		0: "MESSAGE_ROLE_UNSPECIFIED",
		1: "MESSAGE_ROLE_USER",
		2: "MESSAGE_ROLE_ASSISTANT",
	}
	MessageRole_value = map[string]int32{
		"MESSAGE_ROLE_UNSPECIFIED": 0,
		"MESSAGE_ROLE_USER":        1,
		"MESSAGE_ROLE_ASSISTANT":   2,
	}
)

func (x MessageRole) Enum() *MessageRole {
	p := new(MessageRole)
	*p = x
	return p
}

func (x MessageRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageRole) Descriptor() protoreflect.EnumDescriptor {
	return file_construct_v1_message_proto_enumTypes[0].Descriptor()
}

func (MessageRole) Type() protoreflect.EnumType {
	return &file_construct_v1_message_proto_enumTypes[0]
}

func (x MessageRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageRole.Descriptor instead.
func (MessageRole) EnumDescriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata      *MessageMetadata       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_construct_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetMetadata() *MessageMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type MessageMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ModelId       string                 `protobuf:"bytes,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Role          MessageRole            `protobuf:"varint,1,opt,name=role,proto3,enum=construct.v1.MessageRole" json:"role,omitempty"`
	Usage         *MessageUsage          `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageMetadata) Reset() {
	*x = MessageMetadata{}
	mi := &file_construct_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageMetadata) ProtoMessage() {}

func (x *MessageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageMetadata.ProtoReflect.Descriptor instead.
func (*MessageMetadata) Descriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MessageMetadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *MessageMetadata) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MessageMetadata) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MessageMetadata) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *MessageMetadata) GetRole() MessageRole {
	if x != nil {
		return x.Role
	}
	return MessageRole_MESSAGE_ROLE_UNSPECIFIED
}

func (x *MessageMetadata) GetUsage() *MessageUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type MessageUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InputTokens      int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens     int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheWriteTokens int64                  `protobuf:"varint,3,opt,name=cache_write_tokens,json=cacheWriteTokens,proto3" json:"cache_write_tokens,omitempty"`
	CacheReadTokens  int64                  `protobuf:"varint,4,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	Cost             float64                `protobuf:"fixed64,5,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MessageUsage) Reset() {
	*x = MessageUsage{}
	mi := &file_construct_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUsage) ProtoMessage() {}

func (x *MessageUsage) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUsage.ProtoReflect.Descriptor instead.
func (*MessageUsage) Descriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *MessageUsage) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *MessageUsage) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *MessageUsage) GetCacheWriteTokens() int64 {
	if x != nil {
		return x.CacheWriteTokens
	}
	return 0
}

func (x *MessageUsage) GetCacheReadTokens() int64 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *MessageUsage) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type CreateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageRequest) Reset() {
	*x = CreateMessageRequest{}
	mi := &file_construct_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRequest) ProtoMessage() {}

func (x *CreateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMessageRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageResponse) Reset() {
	*x = CreateMessageResponse{}
	mi := &file_construct_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageResponse) ProtoMessage() {}

func (x *CreateMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageResponse.ProtoReflect.Descriptor instead.
func (*CreateMessageResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_construct_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageResponse) Reset() {
	*x = GetMessageResponse{}
	mi := &file_construct_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageResponse) ProtoMessage() {}

func (x *GetMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageResponse.ProtoReflect.Descriptor instead.
func (*GetMessageResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *GetMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type ListMessagesRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Filter        *ListMessagesRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageToken     string                      `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_construct_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{7}
}

func (x *ListMessagesRequest) GetFilter() *ListMessagesRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListMessagesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_construct_v1_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{8}
}

func (x *ListMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageRequest) Reset() {
	*x = UpdateMessageRequest{}
	mi := &file_construct_v1_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageRequest) ProtoMessage() {}

func (x *UpdateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageRequest.ProtoReflect.Descriptor instead.
func (*UpdateMessageRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageResponse) Reset() {
	*x = UpdateMessageResponse{}
	mi := &file_construct_v1_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageResponse) ProtoMessage() {}

func (x *UpdateMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageResponse.ProtoReflect.Descriptor instead.
func (*UpdateMessageResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_construct_v1_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	mi := &file_construct_v1_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{12}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_construct_v1_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribeRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*SubscribeResponse_Message
	Event         isSubscribeResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_construct_v1_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{14}
}

func (x *SubscribeResponse) GetEvent() isSubscribeResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SubscribeResponse) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Event.(*SubscribeResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

type isSubscribeResponse_Event interface {
	isSubscribeResponse_Event()
}

type SubscribeResponse_Message struct {
	Message *Message `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

func (*SubscribeResponse_Message) isSubscribeResponse_Event() {}

type ListMessagesRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        *string                `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"`
	AgentId       *string                `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3,oneof" json:"agent_id,omitempty"`
	Role          *MessageRole           `protobuf:"varint,3,opt,name=role,proto3,enum=construct.v1.MessageRole,oneof" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest_Filter) Reset() {
	*x = ListMessagesRequest_Filter{}
	mi := &file_construct_v1_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest_Filter) ProtoMessage() {}

func (x *ListMessagesRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest_Filter) Descriptor() ([]byte, []int) {
	return file_construct_v1_message_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListMessagesRequest_Filter) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

func (x *ListMessagesRequest_Filter) GetAgentId() string {
	if x != nil && x.AgentId != nil {
		return *x.AgentId
	}
	return ""
}

func (x *ListMessagesRequest_Filter) GetRole() MessageRole {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return MessageRole_MESSAGE_ROLE_UNSPECIFIED
}

var File_construct_v1_message_proto protoreflect.FileDescriptor

const file_construct_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1aconstruct/v1/message.proto\x12\fconstruct.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"x\n" +
	"\aMessage\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x129\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1d.construct.v1.MessageMetadataR\bmetadata\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\xe5\x02\n" +
	"\x0fMessageMetadata\x12A\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tcreatedAt\x12A\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tupdatedAt\x12!\n" +
	"\atask_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06taskId\x12#\n" +
	"\bagent_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aagentId\x12#\n" +
	"\bmodel_id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\amodelId\x12-\n" +
	"\x04role\x18\x01 \x01(\x0e2\x19.construct.v1.MessageRoleR\x04role\x120\n" +
	"\x05usage\x18\x05 \x01(\v2\x1a.construct.v1.MessageUsageR\x05usage\"\xc4\x01\n" +
	"\fMessageUsage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\x12,\n" +
	"\x12cache_write_tokens\x18\x03 \x01(\x03R\x10cacheWriteTokens\x12*\n" +
	"\x11cache_read_tokens\x18\x04 \x01(\x03R\x0fcacheReadTokens\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x01R\x04cost\"\\\n" +
	"\x14CreateMessageRequest\x12!\n" +
	"\atask_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06taskId\x12!\n" +
	"\acontent\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\acontent\"P\n" +
	"\x15CreateMessageResponse\x127\n" +
	"\amessage\x18\x01 \x01(\v2\x15.construct.v1.MessageB\x06\xbaH\x03\xc8\x01\x01R\amessage\"-\n" +
	"\x11GetMessageRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"M\n" +
	"\x12GetMessageResponse\x127\n" +
	"\amessage\x18\x01 \x01(\v2\x15.construct.v1.MessageB\x06\xbaH\x03\xc8\x01\x01R\amessage\"\xb3\x02\n" +
	"\x13ListMessagesRequest\x12@\n" +
	"\x06filter\x18\x01 \x01(\v2(.construct.v1.ListMessagesRequest.FilterR\x06filter\x12'\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\tpageToken\x1a\xb0\x01\n" +
	"\x06Filter\x12&\n" +
	"\atask_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\x06taskId\x88\x01\x01\x12(\n" +
	"\bagent_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x01R\aagentId\x88\x01\x01\x122\n" +
	"\x04role\x18\x03 \x01(\x0e2\x19.construct.v1.MessageRoleH\x02R\x04role\x88\x01\x01B\n" +
	"\n" +
	"\b_task_idB\v\n" +
	"\t_agent_idB\a\n" +
	"\x05_role\"q\n" +
	"\x14ListMessagesResponse\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.construct.v1.MessageR\bmessages\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"S\n" +
	"\x14UpdateMessageRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12!\n" +
	"\acontent\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\acontent\"P\n" +
	"\x15UpdateMessageResponse\x127\n" +
	"\amessage\x18\x01 \x01(\v2\x15.construct.v1.MessageB\x06\xbaH\x03\xc8\x01\x01R\amessage\"0\n" +
	"\x14DeleteMessageRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"\x17\n" +
	"\x15DeleteMessageResponse\"5\n" +
	"\x10SubscribeRequest\x12!\n" +
	"\atask_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06taskId\"O\n" +
	"\x11SubscribeResponse\x121\n" +
	"\amessage\x18\x01 \x01(\v2\x15.construct.v1.MessageH\x00R\amessageB\a\n" +
	"\x05event*^\n" +
	"\vMessageRole\x12\x1c\n" +
	"\x18MESSAGE_ROLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_ROLE_USER\x10\x01\x12\x1a\n" +
	"\x16MESSAGE_ROLE_ASSISTANT\x10\x022\xa8\x04\n" +
	"\x0eMessageService\x12Z\n" +
	"\rCreateMessage\x12\".construct.v1.CreateMessageRequest\x1a#.construct.v1.CreateMessageResponse\"\x00\x12T\n" +
	"\n" +
	"GetMessage\x12\x1f.construct.v1.GetMessageRequest\x1a .construct.v1.GetMessageResponse\"\x03\x90\x02\x01\x12Z\n" +
	"\fListMessages\x12!.construct.v1.ListMessagesRequest\x1a\".construct.v1.ListMessagesResponse\"\x03\x90\x02\x01\x12Z\n" +
	"\rUpdateMessage\x12\".construct.v1.UpdateMessageRequest\x1a#.construct.v1.UpdateMessageResponse\"\x00\x12Z\n" +
	"\rDeleteMessage\x12\".construct.v1.DeleteMessageRequest\x1a#.construct.v1.DeleteMessageResponse\"\x00\x12P\n" +
	"\tSubscribe\x12\x1e.construct.v1.SubscribeRequest\x1a\x1f.construct.v1.SubscribeResponse\"\x000\x01B(Z&github.com/furisto/construct/api/go/v1b\x06proto3"

var (
	file_construct_v1_message_proto_rawDescOnce sync.Once
	file_construct_v1_message_proto_rawDescData []byte
)

func file_construct_v1_message_proto_rawDescGZIP() []byte {
	file_construct_v1_message_proto_rawDescOnce.Do(func() {
		file_construct_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_construct_v1_message_proto_rawDesc), len(file_construct_v1_message_proto_rawDesc)))
	})
	return file_construct_v1_message_proto_rawDescData
}

var file_construct_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_construct_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_construct_v1_message_proto_goTypes = []any{
	(MessageRole)(0),                   // 0: construct.v1.MessageRole
	(*Message)(nil),                    // 1: construct.v1.Message
	(*MessageMetadata)(nil),            // 2: construct.v1.MessageMetadata
	(*MessageUsage)(nil),               // 3: construct.v1.MessageUsage
	(*CreateMessageRequest)(nil),       // 4: construct.v1.CreateMessageRequest
	(*CreateMessageResponse)(nil),      // 5: construct.v1.CreateMessageResponse
	(*GetMessageRequest)(nil),          // 6: construct.v1.GetMessageRequest
	(*GetMessageResponse)(nil),         // 7: construct.v1.GetMessageResponse
	(*ListMessagesRequest)(nil),        // 8: construct.v1.ListMessagesRequest
	(*ListMessagesResponse)(nil),       // 9: construct.v1.ListMessagesResponse
	(*UpdateMessageRequest)(nil),       // 10: construct.v1.UpdateMessageRequest
	(*UpdateMessageResponse)(nil),      // 11: construct.v1.UpdateMessageResponse
	(*DeleteMessageRequest)(nil),       // 12: construct.v1.DeleteMessageRequest
	(*DeleteMessageResponse)(nil),      // 13: construct.v1.DeleteMessageResponse
	(*SubscribeRequest)(nil),           // 14: construct.v1.SubscribeRequest
	(*SubscribeResponse)(nil),          // 15: construct.v1.SubscribeResponse
	(*ListMessagesRequest_Filter)(nil), // 16: construct.v1.ListMessagesRequest.Filter
	(*timestamppb.Timestamp)(nil),      // 17: google.protobuf.Timestamp
}
var file_construct_v1_message_proto_depIdxs = []int32{
	2,  // 0: construct.v1.Message.metadata:type_name -> construct.v1.MessageMetadata
	17, // 1: construct.v1.MessageMetadata.created_at:type_name -> google.protobuf.Timestamp
	17, // 2: construct.v1.MessageMetadata.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: construct.v1.MessageMetadata.role:type_name -> construct.v1.MessageRole
	3,  // 4: construct.v1.MessageMetadata.usage:type_name -> construct.v1.MessageUsage
	1,  // 5: construct.v1.CreateMessageResponse.message:type_name -> construct.v1.Message
	1,  // 6: construct.v1.GetMessageResponse.message:type_name -> construct.v1.Message
	16, // 7: construct.v1.ListMessagesRequest.filter:type_name -> construct.v1.ListMessagesRequest.Filter
	1,  // 8: construct.v1.ListMessagesResponse.messages:type_name -> construct.v1.Message
	1,  // 9: construct.v1.UpdateMessageResponse.message:type_name -> construct.v1.Message
	1,  // 10: construct.v1.SubscribeResponse.message:type_name -> construct.v1.Message
	0,  // 11: construct.v1.ListMessagesRequest.Filter.role:type_name -> construct.v1.MessageRole
	4,  // 12: construct.v1.MessageService.CreateMessage:input_type -> construct.v1.CreateMessageRequest
	6,  // 13: construct.v1.MessageService.GetMessage:input_type -> construct.v1.GetMessageRequest
	8,  // 14: construct.v1.MessageService.ListMessages:input_type -> construct.v1.ListMessagesRequest
	10, // 15: construct.v1.MessageService.UpdateMessage:input_type -> construct.v1.UpdateMessageRequest
	12, // 16: construct.v1.MessageService.DeleteMessage:input_type -> construct.v1.DeleteMessageRequest
	14, // 17: construct.v1.MessageService.Subscribe:input_type -> construct.v1.SubscribeRequest
	5,  // 18: construct.v1.MessageService.CreateMessage:output_type -> construct.v1.CreateMessageResponse
	7,  // 19: construct.v1.MessageService.GetMessage:output_type -> construct.v1.GetMessageResponse
	9,  // 20: construct.v1.MessageService.ListMessages:output_type -> construct.v1.ListMessagesResponse
	11, // 21: construct.v1.MessageService.UpdateMessage:output_type -> construct.v1.UpdateMessageResponse
	13, // 22: construct.v1.MessageService.DeleteMessage:output_type -> construct.v1.DeleteMessageResponse
	15, // 23: construct.v1.MessageService.Subscribe:output_type -> construct.v1.SubscribeResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_construct_v1_message_proto_init() }
func file_construct_v1_message_proto_init() {
	if File_construct_v1_message_proto != nil {
		return
	}
	file_construct_v1_message_proto_msgTypes[14].OneofWrappers = []any{
		(*SubscribeResponse_Message)(nil),
	}
	file_construct_v1_message_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_construct_v1_message_proto_rawDesc), len(file_construct_v1_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_construct_v1_message_proto_goTypes,
		DependencyIndexes: file_construct_v1_message_proto_depIdxs,
		EnumInfos:         file_construct_v1_message_proto_enumTypes,
		MessageInfos:      file_construct_v1_message_proto_msgTypes,
	}.Build()
	File_construct_v1_message_proto = out.File
	file_construct_v1_message_proto_goTypes = nil
	file_construct_v1_message_proto_depIdxs = nil
}
