// Skill API provides operations for managing skills within Construct.
// Skills are specialized instructions that extend agent capabilities. They can be
// installed from remote repositories (GitHub, GitLab) or direct URLs.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: construct/v1/skill.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GitProvider identifies the git hosting service.
type GitProvider int32

const (
	// GIT_PROVIDER_UNSPECIFIED indicates an unknown provider.
	GitProvider_GIT_PROVIDER_UNSPECIFIED GitProvider = 0
	// GIT_PROVIDER_GITHUB indicates GitHub.
	GitProvider_GIT_PROVIDER_GITHUB GitProvider = 1
	// GIT_PROVIDER_GITLAB indicates GitLab.
	GitProvider_GIT_PROVIDER_GITLAB GitProvider = 2
)

// Enum value maps for GitProvider.
var (
	GitProvider_name = map[int32]string{
		0: "GIT_PROVIDER_UNSPECIFIED",
		1: "GIT_PROVIDER_GITHUB",
		2: "GIT_PROVIDER_GITLAB",
	}
	GitProvider_value = map[string]int32{
		"GIT_PROVIDER_UNSPECIFIED": 0,
		"GIT_PROVIDER_GITHUB":      1,
		"GIT_PROVIDER_GITLAB":      2,
	}
)

func (x GitProvider) Enum() *GitProvider {
	p := new(GitProvider)
	*p = x
	return p
}

func (x GitProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GitProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_construct_v1_skill_proto_enumTypes[0].Descriptor()
}

func (GitProvider) Type() protoreflect.EnumType {
	return &file_construct_v1_skill_proto_enumTypes[0]
}

func (x GitProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GitProvider.Descriptor instead.
func (GitProvider) EnumDescriptor() ([]byte, []int) {
	return file_construct_v1_skill_proto_rawDescGZIP(), []int{0}
}

// Skill represents an installed skill with its metadata and source information.
type Skill struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique identifier for the skill (lowercase alphanumeric with hyphens).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description provides a brief summary of the skill's purpose.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// installed_at is the timestamp when the skill was first installed.
	InstalledAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=installed_at,json=installedAt,proto3" json:"installed_at,omitempty"`
	// updated_at is the timestamp when the skill was last updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// source indicates where the skill was installed from.
	// If not set, the skill was manually placed (local).
	//
	// Types that are valid to be assigned to Source:
	//
	//	*Skill_Git
	//	*Skill_Url
	Source        isSkill_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_construct_v1_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_construct_v1_skill_proto_rawDescGZIP(), []int{0}
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Skill) GetInstalledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InstalledAt
	}
	return nil
}

func (x *Skill) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Skill) GetSource() isSkill_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Skill) GetGit() *GitSource {
	if x != nil {
		if x, ok := x.Source.(*Skill_Git); ok {
			return x.Git
		}
	}
	return nil
}

func (x *Skill) GetUrl() *UrlSource {
	if x != nil {
		if x, ok := x.Source.(*Skill_Url); ok {
			return x.Url
		}
	}
	return nil
}

type isSkill_Source interface {
	isSkill_Source()
}

type Skill_Git struct {
	Git *GitSource `protobuf:"bytes,5,opt,name=git,proto3,oneof"`
}

type Skill_Url struct {
	Url *UrlSource `protobuf:"bytes,6,opt,name=url,proto3,oneof"`
}

func (*Skill_Git) isSkill_Source() {}

func (*Skill_Url) isSkill_Source() {}

// GitSource represents a skill installed from a git repository.
type GitSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// provider indicates which git hosting service the skill came from.
	Provider GitProvider `protobuf:"varint,1,opt,name=provider,proto3,enum=construct.v1.GitProvider" json:"provider,omitempty"`
	// clone_url is the HTTPS URL used to clone the repository.
	CloneUrl string `protobuf:"bytes,2,opt,name=clone_url,json=cloneUrl,proto3" json:"clone_url,omitempty"`
	// path is the path within the repository to the skill directory.
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// ref is the branch or tag that was checked out.
	Ref string `protobuf:"bytes,4,opt,name=ref,proto3" json:"ref,omitempty"`
	// tree_hash is the git tree hash for detecting updates.
	TreeHash      string `protobuf:"bytes,5,opt,name=tree_hash,json=treeHash,proto3" json:"tree_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitSource) Reset() {
	*x = GitSource{}
	mi := &file_construct_v1_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitSource) ProtoMessage() {}

func (x *GitSource) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitSource.ProtoReflect.Descriptor instead.
func (*GitSource) Descriptor() ([]byte, []int) {
	return file_construct_v1_skill_proto_rawDescGZIP(), []int{1}
}

func (x *GitSource) GetProvider() GitProvider {
	if x != nil {
		return x.Provider
	}
	return GitProvider_GIT_PROVIDER_UNSPECIFIED
}

func (x *GitSource) GetCloneUrl() string {
	if x != nil {
		return x.CloneUrl
	}
	return ""
}

func (x *GitSource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GitSource) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *GitSource) GetTreeHash() string {
	if x != nil {
		return x.TreeHash
	}
	return ""
}

// UrlSource represents a skill installed from a direct URL.
type UrlSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// url is the direct URL to the SKILL.md file.
	Url           string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlSource) Reset() {
	*x = UrlSource{}
	mi := &file_construct_v1_skill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlSource) ProtoMessage() {}

func (x *UrlSource) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_skill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlSource.ProtoReflect.Descriptor instead.
func (*UrlSource) Descriptor() ([]byte, []int) {
	return file_construct_v1_skill_proto_rawDescGZIP(), []int{2}
}

func (x *UrlSource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// ListSkillsRequest specifies parameters for listing installed skills.
type ListSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsRequest) Reset() {
	*x = ListSkillsRequest{}
	mi := &file_construct_v1_skill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsRequest) ProtoMessage() {}

func (x *ListSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_skill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsRequest.ProtoReflect.Descriptor instead.
func (*ListSkillsRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_skill_proto_rawDescGZIP(), []int{3}
}

// ListSkillsResponse contains the list of installed skills.
type ListSkillsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// skills is the list of installed skills.
	Skills        []*Skill `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsResponse) Reset() {
	*x = ListSkillsResponse{}
	mi := &file_construct_v1_skill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsResponse) ProtoMessage() {}

func (x *ListSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_skill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsResponse.ProtoReflect.Descriptor instead.
func (*ListSkillsResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_skill_proto_rawDescGZIP(), []int{4}
}

func (x *ListSkillsResponse) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

// InstallSkillRequest specifies the source to install skills from.
type InstallSkillRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// source is the installation source (e.g., "owner/repo", "github.com/owner/repo/tree/branch/path",
	// or a direct URL ending in SKILL.md).
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// force overwrites existing skills if they already exist.
	Force bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	// skill_names filters which skills to install from the source.
	// If empty, all discovered skills are installed.
	SkillNames    []string `protobuf:"bytes,3,rep,name=skill_names,json=skillNames,proto3" json:"skill_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSkillRequest) Reset() {
	*x = InstallSkillRequest{}
	mi := &file_construct_v1_skill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSkillRequest) ProtoMessage() {}

func (x *InstallSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_skill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSkillRequest.ProtoReflect.Descriptor instead.
func (*InstallSkillRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_skill_proto_rawDescGZIP(), []int{5}
}

func (x *InstallSkillRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *InstallSkillRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *InstallSkillRequest) GetSkillNames() []string {
	if x != nil {
		return x.SkillNames
	}
	return nil
}

// InstallSkillResponse contains the results of the installation.
type InstallSkillResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// installed_skills is the list of skills that were successfully installed.
	InstalledSkills []*Skill `protobuf:"bytes,1,rep,name=installed_skills,json=installedSkills,proto3" json:"installed_skills,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InstallSkillResponse) Reset() {
	*x = InstallSkillResponse{}
	mi := &file_construct_v1_skill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSkillResponse) ProtoMessage() {}

func (x *InstallSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_skill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSkillResponse.ProtoReflect.Descriptor instead.
func (*InstallSkillResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_skill_proto_rawDescGZIP(), []int{6}
}

func (x *InstallSkillResponse) GetInstalledSkills() []*Skill {
	if x != nil {
		return x.InstalledSkills
	}
	return nil
}

// DeleteSkillRequest specifies which skill to delete.
type DeleteSkillRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name of the skill to delete.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkillRequest) Reset() {
	*x = DeleteSkillRequest{}
	mi := &file_construct_v1_skill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkillRequest) ProtoMessage() {}

func (x *DeleteSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_skill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkillRequest.ProtoReflect.Descriptor instead.
func (*DeleteSkillRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_skill_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DeleteSkillResponse confirms the skill deletion (empty response).
type DeleteSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkillResponse) Reset() {
	*x = DeleteSkillResponse{}
	mi := &file_construct_v1_skill_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkillResponse) ProtoMessage() {}

func (x *DeleteSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_skill_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkillResponse.ProtoReflect.Descriptor instead.
func (*DeleteSkillResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_skill_proto_rawDescGZIP(), []int{8}
}

// UpdateSkillRequest specifies which skills to update.
type UpdateSkillRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name of a specific skill to update.
	// If empty, all skills with remote sources are updated.
	Name          *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSkillRequest) Reset() {
	*x = UpdateSkillRequest{}
	mi := &file_construct_v1_skill_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkillRequest) ProtoMessage() {}

func (x *UpdateSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_skill_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkillRequest.ProtoReflect.Descriptor instead.
func (*UpdateSkillRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_skill_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSkillRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// UpdateSkillResponse contains the results of the update.
type UpdateSkillResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// updated_skills is the list of skills that were successfully updated.
	UpdatedSkills []*Skill `protobuf:"bytes,1,rep,name=updated_skills,json=updatedSkills,proto3" json:"updated_skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSkillResponse) Reset() {
	*x = UpdateSkillResponse{}
	mi := &file_construct_v1_skill_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkillResponse) ProtoMessage() {}

func (x *UpdateSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_skill_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkillResponse.ProtoReflect.Descriptor instead.
func (*UpdateSkillResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_skill_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSkillResponse) GetUpdatedSkills() []*Skill {
	if x != nil {
		return x.UpdatedSkills
	}
	return nil
}

var File_construct_v1_skill_proto protoreflect.FileDescriptor

const file_construct_v1_skill_proto_rawDesc = "" +
	"\n" +
	"\x18construct/v1/skill.proto\x12\fconstruct.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x02\n" +
	"\x05Skill\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12=\n" +
	"\finstalled_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vinstalledAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12+\n" +
	"\x03git\x18\x05 \x01(\v2\x17.construct.v1.GitSourceH\x00R\x03git\x12+\n" +
	"\x03url\x18\x06 \x01(\v2\x17.construct.v1.UrlSourceH\x00R\x03urlB\b\n" +
	"\x06source\"\xbe\x01\n" +
	"\tGitSource\x12?\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x19.construct.v1.GitProviderB\b\xbaH\x05\x82\x01\x02\x10\x01R\bprovider\x12$\n" +
	"\tclone_url\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bcloneUrl\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x19\n" +
	"\x03ref\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03ref\x12\x1b\n" +
	"\ttree_hash\x18\x05 \x01(\tR\btreeHash\"&\n" +
	"\tUrlSource\x12\x19\n" +
	"\x03url\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03url\"\x13\n" +
	"\x11ListSkillsRequest\"A\n" +
	"\x12ListSkillsResponse\x12+\n" +
	"\x06skills\x18\x01 \x03(\v2\x13.construct.v1.SkillR\x06skills\"m\n" +
	"\x13InstallSkillRequest\x12\x1f\n" +
	"\x06source\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06source\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12\x1f\n" +
	"\vskill_names\x18\x03 \x03(\tR\n" +
	"skillNames\"V\n" +
	"\x14InstallSkillResponse\x12>\n" +
	"\x10installed_skills\x18\x01 \x03(\v2\x13.construct.v1.SkillR\x0finstalledSkills\"1\n" +
	"\x12DeleteSkillRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\"\x15\n" +
	"\x13DeleteSkillResponse\"6\n" +
	"\x12UpdateSkillRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"Q\n" +
	"\x13UpdateSkillResponse\x12:\n" +
	"\x0eupdated_skills\x18\x01 \x03(\v2\x13.construct.v1.SkillR\rupdatedSkills*]\n" +
	"\vGitProvider\x12\x1c\n" +
	"\x18GIT_PROVIDER_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13GIT_PROVIDER_GITHUB\x10\x01\x12\x17\n" +
	"\x13GIT_PROVIDER_GITLAB\x10\x022\xe9\x02\n" +
	"\fSkillService\x12W\n" +
	"\fInstallSkill\x12!.construct.v1.InstallSkillRequest\x1a\".construct.v1.InstallSkillResponse\"\x00\x12T\n" +
	"\n" +
	"ListSkills\x12\x1f.construct.v1.ListSkillsRequest\x1a .construct.v1.ListSkillsResponse\"\x03\x90\x02\x01\x12T\n" +
	"\vDeleteSkill\x12 .construct.v1.DeleteSkillRequest\x1a!.construct.v1.DeleteSkillResponse\"\x00\x12T\n" +
	"\vUpdateSkill\x12 .construct.v1.UpdateSkillRequest\x1a!.construct.v1.UpdateSkillResponse\"\x00B(Z&github.com/furisto/construct/api/go/v1b\x06proto3"

var (
	file_construct_v1_skill_proto_rawDescOnce sync.Once
	file_construct_v1_skill_proto_rawDescData []byte
)

func file_construct_v1_skill_proto_rawDescGZIP() []byte {
	file_construct_v1_skill_proto_rawDescOnce.Do(func() {
		file_construct_v1_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_construct_v1_skill_proto_rawDesc), len(file_construct_v1_skill_proto_rawDesc)))
	})
	return file_construct_v1_skill_proto_rawDescData
}

var file_construct_v1_skill_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_construct_v1_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_construct_v1_skill_proto_goTypes = []any{
	(GitProvider)(0),              // 0: construct.v1.GitProvider
	(*Skill)(nil),                 // 1: construct.v1.Skill
	(*GitSource)(nil),             // 2: construct.v1.GitSource
	(*UrlSource)(nil),             // 3: construct.v1.UrlSource
	(*ListSkillsRequest)(nil),     // 4: construct.v1.ListSkillsRequest
	(*ListSkillsResponse)(nil),    // 5: construct.v1.ListSkillsResponse
	(*InstallSkillRequest)(nil),   // 6: construct.v1.InstallSkillRequest
	(*InstallSkillResponse)(nil),  // 7: construct.v1.InstallSkillResponse
	(*DeleteSkillRequest)(nil),    // 8: construct.v1.DeleteSkillRequest
	(*DeleteSkillResponse)(nil),   // 9: construct.v1.DeleteSkillResponse
	(*UpdateSkillRequest)(nil),    // 10: construct.v1.UpdateSkillRequest
	(*UpdateSkillResponse)(nil),   // 11: construct.v1.UpdateSkillResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_construct_v1_skill_proto_depIdxs = []int32{
	12, // 0: construct.v1.Skill.installed_at:type_name -> google.protobuf.Timestamp
	12, // 1: construct.v1.Skill.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: construct.v1.Skill.git:type_name -> construct.v1.GitSource
	3,  // 3: construct.v1.Skill.url:type_name -> construct.v1.UrlSource
	0,  // 4: construct.v1.GitSource.provider:type_name -> construct.v1.GitProvider
	1,  // 5: construct.v1.ListSkillsResponse.skills:type_name -> construct.v1.Skill
	1,  // 6: construct.v1.InstallSkillResponse.installed_skills:type_name -> construct.v1.Skill
	1,  // 7: construct.v1.UpdateSkillResponse.updated_skills:type_name -> construct.v1.Skill
	6,  // 8: construct.v1.SkillService.InstallSkill:input_type -> construct.v1.InstallSkillRequest
	4,  // 9: construct.v1.SkillService.ListSkills:input_type -> construct.v1.ListSkillsRequest
	8,  // 10: construct.v1.SkillService.DeleteSkill:input_type -> construct.v1.DeleteSkillRequest
	10, // 11: construct.v1.SkillService.UpdateSkill:input_type -> construct.v1.UpdateSkillRequest
	7,  // 12: construct.v1.SkillService.InstallSkill:output_type -> construct.v1.InstallSkillResponse
	5,  // 13: construct.v1.SkillService.ListSkills:output_type -> construct.v1.ListSkillsResponse
	9,  // 14: construct.v1.SkillService.DeleteSkill:output_type -> construct.v1.DeleteSkillResponse
	11, // 15: construct.v1.SkillService.UpdateSkill:output_type -> construct.v1.UpdateSkillResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_construct_v1_skill_proto_init() }
func file_construct_v1_skill_proto_init() {
	if File_construct_v1_skill_proto != nil {
		return
	}
	file_construct_v1_skill_proto_msgTypes[0].OneofWrappers = []any{
		(*Skill_Git)(nil),
		(*Skill_Url)(nil),
	}
	file_construct_v1_skill_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_construct_v1_skill_proto_rawDesc), len(file_construct_v1_skill_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_construct_v1_skill_proto_goTypes,
		DependencyIndexes: file_construct_v1_skill_proto_depIdxs,
		EnumInfos:         file_construct_v1_skill_proto_enumTypes,
		MessageInfos:      file_construct_v1_skill_proto_msgTypes,
	}.Build()
	File_construct_v1_skill_proto = out.File
	file_construct_v1_skill_proto_goTypes = nil
	file_construct_v1_skill_proto_depIdxs = nil
}
