// Code generated by ent. DO NOT EDIT.

package memory

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/furisto/construct/backend/memory/agent"
	"github.com/furisto/construct/backend/memory/message"
	"github.com/furisto/construct/backend/memory/model"
	"github.com/furisto/construct/backend/memory/predicate"
	"github.com/furisto/construct/backend/memory/task"
	"github.com/google/uuid"
)

// AgentUpdate is the builder for updating Agent entities.
type AgentUpdate struct {
	config
	hooks    []Hook
	mutation *AgentMutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (au *AgentUpdate) Where(ps ...predicate.Agent) *AgentUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetDefaultModel sets the "default_model" field.
func (au *AgentUpdate) SetDefaultModel(u uuid.UUID) *AgentUpdate {
	au.mutation.SetDefaultModel(u)
	return au
}

// SetNillableDefaultModel sets the "default_model" field if the given value is not nil.
func (au *AgentUpdate) SetNillableDefaultModel(u *uuid.UUID) *AgentUpdate {
	if u != nil {
		au.SetDefaultModel(*u)
	}
	return au
}

// SetModelID sets the "model" edge to the Model entity by ID.
func (au *AgentUpdate) SetModelID(id uuid.UUID) *AgentUpdate {
	au.mutation.SetModelID(id)
	return au
}

// SetModel sets the "model" edge to the Model entity.
func (au *AgentUpdate) SetModel(m *Model) *AgentUpdate {
	return au.SetModelID(m.ID)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (au *AgentUpdate) AddTaskIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.AddTaskIDs(ids...)
	return au
}

// AddTasks adds the "tasks" edges to the Task entity.
func (au *AgentUpdate) AddTasks(t ...*Task) *AgentUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return au.AddTaskIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (au *AgentUpdate) AddMessageIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.AddMessageIDs(ids...)
	return au
}

// AddMessages adds the "messages" edges to the Message entity.
func (au *AgentUpdate) AddMessages(m ...*Message) *AgentUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return au.AddMessageIDs(ids...)
}

// Mutation returns the AgentMutation object of the builder.
func (au *AgentUpdate) Mutation() *AgentMutation {
	return au.mutation
}

// ClearModel clears the "model" edge to the Model entity.
func (au *AgentUpdate) ClearModel() *AgentUpdate {
	au.mutation.ClearModel()
	return au
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (au *AgentUpdate) ClearTasks() *AgentUpdate {
	au.mutation.ClearTasks()
	return au
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (au *AgentUpdate) RemoveTaskIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.RemoveTaskIDs(ids...)
	return au
}

// RemoveTasks removes "tasks" edges to Task entities.
func (au *AgentUpdate) RemoveTasks(t ...*Task) *AgentUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return au.RemoveTaskIDs(ids...)
}

// ClearMessages clears all "messages" edges to the Message entity.
func (au *AgentUpdate) ClearMessages() *AgentUpdate {
	au.mutation.ClearMessages()
	return au
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (au *AgentUpdate) RemoveMessageIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.RemoveMessageIDs(ids...)
	return au
}

// RemoveMessages removes "messages" edges to Message entities.
func (au *AgentUpdate) RemoveMessages(m ...*Message) *AgentUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return au.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AgentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AgentUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AgentUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AgentUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AgentUpdate) check() error {
	if au.mutation.ModelCleared() && len(au.mutation.ModelIDs()) > 0 {
		return errors.New(`memory: clearing a required unique edge "Agent.model"`)
	}
	return nil
}

func (au *AgentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if au.mutation.ModelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   agent.ModelTable,
			Columns: []string{agent.ModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.ModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   agent.ModelTable,
			Columns: []string{agent.ModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.TasksTable,
			Columns: []string{agent.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedTasksIDs(); len(nodes) > 0 && !au.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.TasksTable,
			Columns: []string{agent.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.TasksTable,
			Columns: []string{agent.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.MessagesTable,
			Columns: []string{agent.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !au.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.MessagesTable,
			Columns: []string{agent.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.MessagesTable,
			Columns: []string{agent.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AgentUpdateOne is the builder for updating a single Agent entity.
type AgentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentMutation
}

// SetDefaultModel sets the "default_model" field.
func (auo *AgentUpdateOne) SetDefaultModel(u uuid.UUID) *AgentUpdateOne {
	auo.mutation.SetDefaultModel(u)
	return auo
}

// SetNillableDefaultModel sets the "default_model" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableDefaultModel(u *uuid.UUID) *AgentUpdateOne {
	if u != nil {
		auo.SetDefaultModel(*u)
	}
	return auo
}

// SetModelID sets the "model" edge to the Model entity by ID.
func (auo *AgentUpdateOne) SetModelID(id uuid.UUID) *AgentUpdateOne {
	auo.mutation.SetModelID(id)
	return auo
}

// SetModel sets the "model" edge to the Model entity.
func (auo *AgentUpdateOne) SetModel(m *Model) *AgentUpdateOne {
	return auo.SetModelID(m.ID)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (auo *AgentUpdateOne) AddTaskIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.AddTaskIDs(ids...)
	return auo
}

// AddTasks adds the "tasks" edges to the Task entity.
func (auo *AgentUpdateOne) AddTasks(t ...*Task) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return auo.AddTaskIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (auo *AgentUpdateOne) AddMessageIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.AddMessageIDs(ids...)
	return auo
}

// AddMessages adds the "messages" edges to the Message entity.
func (auo *AgentUpdateOne) AddMessages(m ...*Message) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return auo.AddMessageIDs(ids...)
}

// Mutation returns the AgentMutation object of the builder.
func (auo *AgentUpdateOne) Mutation() *AgentMutation {
	return auo.mutation
}

// ClearModel clears the "model" edge to the Model entity.
func (auo *AgentUpdateOne) ClearModel() *AgentUpdateOne {
	auo.mutation.ClearModel()
	return auo
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (auo *AgentUpdateOne) ClearTasks() *AgentUpdateOne {
	auo.mutation.ClearTasks()
	return auo
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (auo *AgentUpdateOne) RemoveTaskIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.RemoveTaskIDs(ids...)
	return auo
}

// RemoveTasks removes "tasks" edges to Task entities.
func (auo *AgentUpdateOne) RemoveTasks(t ...*Task) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return auo.RemoveTaskIDs(ids...)
}

// ClearMessages clears all "messages" edges to the Message entity.
func (auo *AgentUpdateOne) ClearMessages() *AgentUpdateOne {
	auo.mutation.ClearMessages()
	return auo
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (auo *AgentUpdateOne) RemoveMessageIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.RemoveMessageIDs(ids...)
	return auo
}

// RemoveMessages removes "messages" edges to Message entities.
func (auo *AgentUpdateOne) RemoveMessages(m ...*Message) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return auo.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the AgentUpdate builder.
func (auo *AgentUpdateOne) Where(ps ...predicate.Agent) *AgentUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AgentUpdateOne) Select(field string, fields ...string) *AgentUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Agent entity.
func (auo *AgentUpdateOne) Save(ctx context.Context) (*Agent, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AgentUpdateOne) SaveX(ctx context.Context) *Agent {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AgentUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AgentUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AgentUpdateOne) check() error {
	if auo.mutation.ModelCleared() && len(auo.mutation.ModelIDs()) > 0 {
		return errors.New(`memory: clearing a required unique edge "Agent.model"`)
	}
	return nil
}

func (auo *AgentUpdateOne) sqlSave(ctx context.Context) (_node *Agent, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`memory: missing "Agent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agent.FieldID)
		for _, f := range fields {
			if !agent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("memory: invalid field %q for query", f)}
			}
			if f != agent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if auo.mutation.ModelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   agent.ModelTable,
			Columns: []string{agent.ModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.ModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   agent.ModelTable,
			Columns: []string{agent.ModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.TasksTable,
			Columns: []string{agent.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedTasksIDs(); len(nodes) > 0 && !auo.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.TasksTable,
			Columns: []string{agent.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.TasksTable,
			Columns: []string{agent.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.MessagesTable,
			Columns: []string{agent.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !auo.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.MessagesTable,
			Columns: []string{agent.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   agent.MessagesTable,
			Columns: []string{agent.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Agent{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
