// Code generated by ent from db_driver.tmpl. DO NOT EDIT.

package memory

import (
	"database/sql"

	"entgo.io/ent/dialect"
	entsql "entgo.io/ent/dialect/sql"
)

// DB returns the underlying *sql.DB, or nil if the driver is not *entsql.Driver
func (c *Client) DB() *sql.DB {
	if drv, ok := c.driver.(*entsql.Driver); ok {
		return drv.DB()
	}
	return nil
}

// MustDB returns the underlying *sql.DB or panics if the driver is not *entsql.Driver
func (c *Client) MustDB() *sql.DB {
	db := c.DB()
	if db == nil {
		panic("memory: client driver is not *entsql.Driver")
	}
	return db
}

// Driver returns the underlying dialect.Driver
func (c *Client) Driver() dialect.Driver {
	return c.driver
}
