//go:build ignore
// +build ignore

package main

import (
	"log/slog"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
	"github.com/hedwigz/entviz"
)

func main() {
	cfg := gen.Config{
		Header: "// Code generated by ent. DO NOT EDIT.",
		Features: []gen.Feature{
			gen.FeatureModifier,
		},	
	}

	options := []entc.Option{
		entc.Extensions(entviz.Extension{}),
		entc.TemplateDir("./templates"),
	}

	if err := entc.Generate("./schema", &cfg, options...); err != nil {
		slog.Error("running ent codegen", "error", err)
	}
}
