// Code generated by ent. DO NOT EDIT.

package memory

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/furisto/construct/backend/memory/modelprovider"
	"github.com/furisto/construct/backend/memory/predicate"
)

// ModelProviderUpdate is the builder for updating ModelProvider entities.
type ModelProviderUpdate struct {
	config
	hooks    []Hook
	mutation *ModelProviderMutation
}

// Where appends a list predicates to the ModelProviderUpdate builder.
func (mpu *ModelProviderUpdate) Where(ps ...predicate.ModelProvider) *ModelProviderUpdate {
	mpu.mutation.Where(ps...)
	return mpu
}

// SetUpdateTime sets the "update_time" field.
func (mpu *ModelProviderUpdate) SetUpdateTime(t time.Time) *ModelProviderUpdate {
	mpu.mutation.SetUpdateTime(t)
	return mpu
}

// SetName sets the "name" field.
func (mpu *ModelProviderUpdate) SetName(s string) *ModelProviderUpdate {
	mpu.mutation.SetName(s)
	return mpu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (mpu *ModelProviderUpdate) SetNillableName(s *string) *ModelProviderUpdate {
	if s != nil {
		mpu.SetName(*s)
	}
	return mpu
}

// Mutation returns the ModelProviderMutation object of the builder.
func (mpu *ModelProviderUpdate) Mutation() *ModelProviderMutation {
	return mpu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mpu *ModelProviderUpdate) Save(ctx context.Context) (int, error) {
	mpu.defaults()
	return withHooks(ctx, mpu.sqlSave, mpu.mutation, mpu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mpu *ModelProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := mpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mpu *ModelProviderUpdate) Exec(ctx context.Context) error {
	_, err := mpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpu *ModelProviderUpdate) ExecX(ctx context.Context) {
	if err := mpu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mpu *ModelProviderUpdate) defaults() {
	if _, ok := mpu.mutation.UpdateTime(); !ok {
		v := modelprovider.UpdateDefaultUpdateTime()
		mpu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mpu *ModelProviderUpdate) check() error {
	if v, ok := mpu.mutation.Name(); ok {
		if err := modelprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`memory: validator failed for field "ModelProvider.name": %w`, err)}
		}
	}
	return nil
}

func (mpu *ModelProviderUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mpu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelprovider.Table, modelprovider.Columns, sqlgraph.NewFieldSpec(modelprovider.FieldID, field.TypeUUID))
	if ps := mpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mpu.mutation.UpdateTime(); ok {
		_spec.SetField(modelprovider.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := mpu.mutation.Name(); ok {
		_spec.SetField(modelprovider.FieldName, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mpu.mutation.done = true
	return n, nil
}

// ModelProviderUpdateOne is the builder for updating a single ModelProvider entity.
type ModelProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelProviderMutation
}

// SetUpdateTime sets the "update_time" field.
func (mpuo *ModelProviderUpdateOne) SetUpdateTime(t time.Time) *ModelProviderUpdateOne {
	mpuo.mutation.SetUpdateTime(t)
	return mpuo
}

// SetName sets the "name" field.
func (mpuo *ModelProviderUpdateOne) SetName(s string) *ModelProviderUpdateOne {
	mpuo.mutation.SetName(s)
	return mpuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (mpuo *ModelProviderUpdateOne) SetNillableName(s *string) *ModelProviderUpdateOne {
	if s != nil {
		mpuo.SetName(*s)
	}
	return mpuo
}

// Mutation returns the ModelProviderMutation object of the builder.
func (mpuo *ModelProviderUpdateOne) Mutation() *ModelProviderMutation {
	return mpuo.mutation
}

// Where appends a list predicates to the ModelProviderUpdate builder.
func (mpuo *ModelProviderUpdateOne) Where(ps ...predicate.ModelProvider) *ModelProviderUpdateOne {
	mpuo.mutation.Where(ps...)
	return mpuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mpuo *ModelProviderUpdateOne) Select(field string, fields ...string) *ModelProviderUpdateOne {
	mpuo.fields = append([]string{field}, fields...)
	return mpuo
}

// Save executes the query and returns the updated ModelProvider entity.
func (mpuo *ModelProviderUpdateOne) Save(ctx context.Context) (*ModelProvider, error) {
	mpuo.defaults()
	return withHooks(ctx, mpuo.sqlSave, mpuo.mutation, mpuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mpuo *ModelProviderUpdateOne) SaveX(ctx context.Context) *ModelProvider {
	node, err := mpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mpuo *ModelProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := mpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpuo *ModelProviderUpdateOne) ExecX(ctx context.Context) {
	if err := mpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mpuo *ModelProviderUpdateOne) defaults() {
	if _, ok := mpuo.mutation.UpdateTime(); !ok {
		v := modelprovider.UpdateDefaultUpdateTime()
		mpuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mpuo *ModelProviderUpdateOne) check() error {
	if v, ok := mpuo.mutation.Name(); ok {
		if err := modelprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`memory: validator failed for field "ModelProvider.name": %w`, err)}
		}
	}
	return nil
}

func (mpuo *ModelProviderUpdateOne) sqlSave(ctx context.Context) (_node *ModelProvider, err error) {
	if err := mpuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelprovider.Table, modelprovider.Columns, sqlgraph.NewFieldSpec(modelprovider.FieldID, field.TypeUUID))
	id, ok := mpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`memory: missing "ModelProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelprovider.FieldID)
		for _, f := range fields {
			if !modelprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("memory: invalid field %q for query", f)}
			}
			if f != modelprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mpuo.mutation.UpdateTime(); ok {
		_spec.SetField(modelprovider.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := mpuo.mutation.Name(); ok {
		_spec.SetField(modelprovider.FieldName, field.TypeString, value)
	}
	_node = &ModelProvider{config: mpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mpuo.mutation.done = true
	return _node, nil
}
