// Code generated by ent. DO NOT EDIT.

package memory

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/furisto/construct/backend/memory/modelprovider"
	"github.com/google/uuid"
)

// ModelProvider is the model entity for the ModelProvider schema.
type ModelProvider struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Name holds the value of the "name" field.
	Name         string `json:"name,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelProvider) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelprovider.FieldName:
			values[i] = new(sql.NullString)
		case modelprovider.FieldCreateTime, modelprovider.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case modelprovider.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelProvider fields.
func (mp *ModelProvider) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelprovider.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				mp.ID = *value
			}
		case modelprovider.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				mp.CreateTime = value.Time
			}
		case modelprovider.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				mp.UpdateTime = value.Time
			}
		case modelprovider.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				mp.Name = value.String
			}
		default:
			mp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelProvider.
// This includes values selected through modifiers, order, etc.
func (mp *ModelProvider) Value(name string) (ent.Value, error) {
	return mp.selectValues.Get(name)
}

// Update returns a builder for updating this ModelProvider.
// Note that you need to call ModelProvider.Unwrap() before calling this method if this ModelProvider
// was returned from a transaction, and the transaction was committed or rolled back.
func (mp *ModelProvider) Update() *ModelProviderUpdateOne {
	return NewModelProviderClient(mp.config).UpdateOne(mp)
}

// Unwrap unwraps the ModelProvider entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mp *ModelProvider) Unwrap() *ModelProvider {
	_tx, ok := mp.config.driver.(*txDriver)
	if !ok {
		panic("memory: ModelProvider is not a transactional entity")
	}
	mp.config.driver = _tx.drv
	return mp
}

// String implements the fmt.Stringer.
func (mp *ModelProvider) String() string {
	var builder strings.Builder
	builder.WriteString("ModelProvider(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mp.ID))
	builder.WriteString("create_time=")
	builder.WriteString(mp.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(mp.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(mp.Name)
	builder.WriteByte(')')
	return builder.String()
}

// ModelProviders is a parsable slice of ModelProvider.
type ModelProviders []*ModelProvider
