// Code generated by ent. DO NOT EDIT.

package memory

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/furisto/construct/backend/memory/agent"
	"github.com/furisto/construct/backend/memory/message"
	"github.com/furisto/construct/backend/memory/model"
	"github.com/furisto/construct/backend/memory/modelprovider"
	"github.com/furisto/construct/backend/memory/predicate"
	"github.com/google/uuid"
)

// ModelUpdate is the builder for updating Model entities.
type ModelUpdate struct {
	config
	hooks    []Hook
	mutation *ModelMutation
}

// Where appends a list predicates to the ModelUpdate builder.
func (mu *ModelUpdate) Where(ps ...predicate.Model) *ModelUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetModelProvider sets the "model_provider" field.
func (mu *ModelUpdate) SetModelProvider(u uuid.UUID) *ModelUpdate {
	mu.mutation.SetModelProvider(u)
	return mu
}

// SetNillableModelProvider sets the "model_provider" field if the given value is not nil.
func (mu *ModelUpdate) SetNillableModelProvider(u *uuid.UUID) *ModelUpdate {
	if u != nil {
		mu.SetModelProvider(*u)
	}
	return mu
}

// AddAgentIDs adds the "agents" edge to the Agent entity by IDs.
func (mu *ModelUpdate) AddAgentIDs(ids ...uuid.UUID) *ModelUpdate {
	mu.mutation.AddAgentIDs(ids...)
	return mu
}

// AddAgents adds the "agents" edges to the Agent entity.
func (mu *ModelUpdate) AddAgents(a ...*Agent) *ModelUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return mu.AddAgentIDs(ids...)
}

// SetModelProvidersID sets the "model_providers" edge to the ModelProvider entity by ID.
func (mu *ModelUpdate) SetModelProvidersID(id uuid.UUID) *ModelUpdate {
	mu.mutation.SetModelProvidersID(id)
	return mu
}

// SetModelProviders sets the "model_providers" edge to the ModelProvider entity.
func (mu *ModelUpdate) SetModelProviders(m *ModelProvider) *ModelUpdate {
	return mu.SetModelProvidersID(m.ID)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (mu *ModelUpdate) AddMessageIDs(ids ...uuid.UUID) *ModelUpdate {
	mu.mutation.AddMessageIDs(ids...)
	return mu
}

// AddMessages adds the "messages" edges to the Message entity.
func (mu *ModelUpdate) AddMessages(m ...*Message) *ModelUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mu.AddMessageIDs(ids...)
}

// Mutation returns the ModelMutation object of the builder.
func (mu *ModelUpdate) Mutation() *ModelMutation {
	return mu.mutation
}

// ClearAgents clears all "agents" edges to the Agent entity.
func (mu *ModelUpdate) ClearAgents() *ModelUpdate {
	mu.mutation.ClearAgents()
	return mu
}

// RemoveAgentIDs removes the "agents" edge to Agent entities by IDs.
func (mu *ModelUpdate) RemoveAgentIDs(ids ...uuid.UUID) *ModelUpdate {
	mu.mutation.RemoveAgentIDs(ids...)
	return mu
}

// RemoveAgents removes "agents" edges to Agent entities.
func (mu *ModelUpdate) RemoveAgents(a ...*Agent) *ModelUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return mu.RemoveAgentIDs(ids...)
}

// ClearModelProviders clears the "model_providers" edge to the ModelProvider entity.
func (mu *ModelUpdate) ClearModelProviders() *ModelUpdate {
	mu.mutation.ClearModelProviders()
	return mu
}

// ClearMessages clears all "messages" edges to the Message entity.
func (mu *ModelUpdate) ClearMessages() *ModelUpdate {
	mu.mutation.ClearMessages()
	return mu
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (mu *ModelUpdate) RemoveMessageIDs(ids ...uuid.UUID) *ModelUpdate {
	mu.mutation.RemoveMessageIDs(ids...)
	return mu
}

// RemoveMessages removes "messages" edges to Message entities.
func (mu *ModelUpdate) RemoveMessages(m ...*Message) *ModelUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mu.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *ModelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *ModelUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *ModelUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *ModelUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *ModelUpdate) check() error {
	if mu.mutation.ModelProvidersCleared() && len(mu.mutation.ModelProvidersIDs()) > 0 {
		return errors.New(`memory: clearing a required unique edge "Model.model_providers"`)
	}
	return nil
}

func (mu *ModelUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(model.Table, model.Columns, sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if mu.mutation.AgentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   model.AgentsTable,
			Columns: []string{model.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedAgentsIDs(); len(nodes) > 0 && !mu.mutation.AgentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   model.AgentsTable,
			Columns: []string{model.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.AgentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   model.AgentsTable,
			Columns: []string{model.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.ModelProvidersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   model.ModelProvidersTable,
			Columns: []string{model.ModelProvidersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelprovider.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.ModelProvidersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   model.ModelProvidersTable,
			Columns: []string{model.ModelProvidersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelprovider.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   model.MessagesTable,
			Columns: []string{model.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !mu.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   model.MessagesTable,
			Columns: []string{model.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   model.MessagesTable,
			Columns: []string{model.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{model.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// ModelUpdateOne is the builder for updating a single Model entity.
type ModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelMutation
}

// SetModelProvider sets the "model_provider" field.
func (muo *ModelUpdateOne) SetModelProvider(u uuid.UUID) *ModelUpdateOne {
	muo.mutation.SetModelProvider(u)
	return muo
}

// SetNillableModelProvider sets the "model_provider" field if the given value is not nil.
func (muo *ModelUpdateOne) SetNillableModelProvider(u *uuid.UUID) *ModelUpdateOne {
	if u != nil {
		muo.SetModelProvider(*u)
	}
	return muo
}

// AddAgentIDs adds the "agents" edge to the Agent entity by IDs.
func (muo *ModelUpdateOne) AddAgentIDs(ids ...uuid.UUID) *ModelUpdateOne {
	muo.mutation.AddAgentIDs(ids...)
	return muo
}

// AddAgents adds the "agents" edges to the Agent entity.
func (muo *ModelUpdateOne) AddAgents(a ...*Agent) *ModelUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return muo.AddAgentIDs(ids...)
}

// SetModelProvidersID sets the "model_providers" edge to the ModelProvider entity by ID.
func (muo *ModelUpdateOne) SetModelProvidersID(id uuid.UUID) *ModelUpdateOne {
	muo.mutation.SetModelProvidersID(id)
	return muo
}

// SetModelProviders sets the "model_providers" edge to the ModelProvider entity.
func (muo *ModelUpdateOne) SetModelProviders(m *ModelProvider) *ModelUpdateOne {
	return muo.SetModelProvidersID(m.ID)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (muo *ModelUpdateOne) AddMessageIDs(ids ...uuid.UUID) *ModelUpdateOne {
	muo.mutation.AddMessageIDs(ids...)
	return muo
}

// AddMessages adds the "messages" edges to the Message entity.
func (muo *ModelUpdateOne) AddMessages(m ...*Message) *ModelUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return muo.AddMessageIDs(ids...)
}

// Mutation returns the ModelMutation object of the builder.
func (muo *ModelUpdateOne) Mutation() *ModelMutation {
	return muo.mutation
}

// ClearAgents clears all "agents" edges to the Agent entity.
func (muo *ModelUpdateOne) ClearAgents() *ModelUpdateOne {
	muo.mutation.ClearAgents()
	return muo
}

// RemoveAgentIDs removes the "agents" edge to Agent entities by IDs.
func (muo *ModelUpdateOne) RemoveAgentIDs(ids ...uuid.UUID) *ModelUpdateOne {
	muo.mutation.RemoveAgentIDs(ids...)
	return muo
}

// RemoveAgents removes "agents" edges to Agent entities.
func (muo *ModelUpdateOne) RemoveAgents(a ...*Agent) *ModelUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return muo.RemoveAgentIDs(ids...)
}

// ClearModelProviders clears the "model_providers" edge to the ModelProvider entity.
func (muo *ModelUpdateOne) ClearModelProviders() *ModelUpdateOne {
	muo.mutation.ClearModelProviders()
	return muo
}

// ClearMessages clears all "messages" edges to the Message entity.
func (muo *ModelUpdateOne) ClearMessages() *ModelUpdateOne {
	muo.mutation.ClearMessages()
	return muo
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (muo *ModelUpdateOne) RemoveMessageIDs(ids ...uuid.UUID) *ModelUpdateOne {
	muo.mutation.RemoveMessageIDs(ids...)
	return muo
}

// RemoveMessages removes "messages" edges to Message entities.
func (muo *ModelUpdateOne) RemoveMessages(m ...*Message) *ModelUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return muo.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the ModelUpdate builder.
func (muo *ModelUpdateOne) Where(ps ...predicate.Model) *ModelUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *ModelUpdateOne) Select(field string, fields ...string) *ModelUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Model entity.
func (muo *ModelUpdateOne) Save(ctx context.Context) (*Model, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *ModelUpdateOne) SaveX(ctx context.Context) *Model {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *ModelUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *ModelUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *ModelUpdateOne) check() error {
	if muo.mutation.ModelProvidersCleared() && len(muo.mutation.ModelProvidersIDs()) > 0 {
		return errors.New(`memory: clearing a required unique edge "Model.model_providers"`)
	}
	return nil
}

func (muo *ModelUpdateOne) sqlSave(ctx context.Context) (_node *Model, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(model.Table, model.Columns, sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`memory: missing "Model.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, model.FieldID)
		for _, f := range fields {
			if !model.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("memory: invalid field %q for query", f)}
			}
			if f != model.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if muo.mutation.AgentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   model.AgentsTable,
			Columns: []string{model.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedAgentsIDs(); len(nodes) > 0 && !muo.mutation.AgentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   model.AgentsTable,
			Columns: []string{model.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.AgentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   model.AgentsTable,
			Columns: []string{model.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.ModelProvidersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   model.ModelProvidersTable,
			Columns: []string{model.ModelProvidersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelprovider.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.ModelProvidersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   model.ModelProvidersTable,
			Columns: []string{model.ModelProvidersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelprovider.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   model.MessagesTable,
			Columns: []string{model.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !muo.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   model.MessagesTable,
			Columns: []string{model.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   model.MessagesTable,
			Columns: []string{model.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Model{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{model.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
