// Code generated by ent. DO NOT EDIT.

package memory

import (
	"time"

	"github.com/furisto/construct/backend/memory/agent"
	"github.com/furisto/construct/backend/memory/message"
	"github.com/furisto/construct/backend/memory/model"
	"github.com/furisto/construct/backend/memory/modelprovider"
	"github.com/furisto/construct/backend/memory/schema"
	"github.com/furisto/construct/backend/memory/task"
	"github.com/furisto/construct/backend/memory/tasksummary"
	"github.com/furisto/construct/backend/memory/token"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentMixin := schema.Agent{}.Mixin()
	agentMixinFields0 := agentMixin[0].Fields()
	_ = agentMixinFields0
	agentFields := schema.Agent{}.Fields()
	_ = agentFields
	// agentDescCreateTime is the schema descriptor for create_time field.
	agentDescCreateTime := agentMixinFields0[0].Descriptor()
	// agent.DefaultCreateTime holds the default value on creation for the create_time field.
	agent.DefaultCreateTime = agentDescCreateTime.Default.(func() time.Time)
	// agentDescUpdateTime is the schema descriptor for update_time field.
	agentDescUpdateTime := agentMixinFields0[1].Descriptor()
	// agent.DefaultUpdateTime holds the default value on creation for the update_time field.
	agent.DefaultUpdateTime = agentDescUpdateTime.Default.(func() time.Time)
	// agent.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	agent.UpdateDefaultUpdateTime = agentDescUpdateTime.UpdateDefault.(func() time.Time)
	// agentDescName is the schema descriptor for name field.
	agentDescName := agentFields[1].Descriptor()
	// agent.NameValidator is a validator for the "name" field. It is called by the builders before save.
	agent.NameValidator = agentDescName.Validators[0].(func(string) error)
	// agentDescBuiltin is the schema descriptor for builtin field.
	agentDescBuiltin := agentFields[4].Descriptor()
	// agent.DefaultBuiltin holds the default value on creation for the builtin field.
	agent.DefaultBuiltin = agentDescBuiltin.Default.(bool)
	// agentDescID is the schema descriptor for id field.
	agentDescID := agentFields[0].Descriptor()
	// agent.DefaultID holds the default value on creation for the id field.
	agent.DefaultID = agentDescID.Default.(func() uuid.UUID)
	messageMixin := schema.Message{}.Mixin()
	messageMixinFields0 := messageMixin[0].Fields()
	_ = messageMixinFields0
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescCreateTime is the schema descriptor for create_time field.
	messageDescCreateTime := messageMixinFields0[0].Descriptor()
	// message.DefaultCreateTime holds the default value on creation for the create_time field.
	message.DefaultCreateTime = messageDescCreateTime.Default.(func() time.Time)
	// messageDescUpdateTime is the schema descriptor for update_time field.
	messageDescUpdateTime := messageMixinFields0[1].Descriptor()
	// message.DefaultUpdateTime holds the default value on creation for the update_time field.
	message.DefaultUpdateTime = messageDescUpdateTime.Default.(func() time.Time)
	// message.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	message.UpdateDefaultUpdateTime = messageDescUpdateTime.UpdateDefault.(func() time.Time)
	// messageDescID is the schema descriptor for id field.
	messageDescID := messageFields[0].Descriptor()
	// message.DefaultID holds the default value on creation for the id field.
	message.DefaultID = messageDescID.Default.(func() uuid.UUID)
	modelMixin := schema.Model{}.Mixin()
	modelMixinFields0 := modelMixin[0].Fields()
	_ = modelMixinFields0
	modelFields := schema.Model{}.Fields()
	_ = modelFields
	// modelDescCreateTime is the schema descriptor for create_time field.
	modelDescCreateTime := modelMixinFields0[0].Descriptor()
	// model.DefaultCreateTime holds the default value on creation for the create_time field.
	model.DefaultCreateTime = modelDescCreateTime.Default.(func() time.Time)
	// modelDescUpdateTime is the schema descriptor for update_time field.
	modelDescUpdateTime := modelMixinFields0[1].Descriptor()
	// model.DefaultUpdateTime holds the default value on creation for the update_time field.
	model.DefaultUpdateTime = modelDescUpdateTime.Default.(func() time.Time)
	// model.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	model.UpdateDefaultUpdateTime = modelDescUpdateTime.UpdateDefault.(func() time.Time)
	// modelDescInputCost is the schema descriptor for input_cost field.
	modelDescInputCost := modelFields[4].Descriptor()
	// model.DefaultInputCost holds the default value on creation for the input_cost field.
	model.DefaultInputCost = modelDescInputCost.Default.(float64)
	// model.InputCostValidator is a validator for the "input_cost" field. It is called by the builders before save.
	model.InputCostValidator = modelDescInputCost.Validators[0].(func(float64) error)
	// modelDescOutputCost is the schema descriptor for output_cost field.
	modelDescOutputCost := modelFields[5].Descriptor()
	// model.DefaultOutputCost holds the default value on creation for the output_cost field.
	model.DefaultOutputCost = modelDescOutputCost.Default.(float64)
	// model.OutputCostValidator is a validator for the "output_cost" field. It is called by the builders before save.
	model.OutputCostValidator = modelDescOutputCost.Validators[0].(func(float64) error)
	// modelDescCacheWriteCost is the schema descriptor for cache_write_cost field.
	modelDescCacheWriteCost := modelFields[6].Descriptor()
	// model.DefaultCacheWriteCost holds the default value on creation for the cache_write_cost field.
	model.DefaultCacheWriteCost = modelDescCacheWriteCost.Default.(float64)
	// model.CacheWriteCostValidator is a validator for the "cache_write_cost" field. It is called by the builders before save.
	model.CacheWriteCostValidator = modelDescCacheWriteCost.Validators[0].(func(float64) error)
	// modelDescCacheReadCost is the schema descriptor for cache_read_cost field.
	modelDescCacheReadCost := modelFields[7].Descriptor()
	// model.DefaultCacheReadCost holds the default value on creation for the cache_read_cost field.
	model.DefaultCacheReadCost = modelDescCacheReadCost.Default.(float64)
	// model.CacheReadCostValidator is a validator for the "cache_read_cost" field. It is called by the builders before save.
	model.CacheReadCostValidator = modelDescCacheReadCost.Validators[0].(func(float64) error)
	// modelDescEnabled is the schema descriptor for enabled field.
	modelDescEnabled := modelFields[8].Descriptor()
	// model.DefaultEnabled holds the default value on creation for the enabled field.
	model.DefaultEnabled = modelDescEnabled.Default.(bool)
	// modelDescID is the schema descriptor for id field.
	modelDescID := modelFields[0].Descriptor()
	// model.DefaultID holds the default value on creation for the id field.
	model.DefaultID = modelDescID.Default.(func() uuid.UUID)
	modelproviderMixin := schema.ModelProvider{}.Mixin()
	modelproviderMixinFields0 := modelproviderMixin[0].Fields()
	_ = modelproviderMixinFields0
	modelproviderFields := schema.ModelProvider{}.Fields()
	_ = modelproviderFields
	// modelproviderDescCreateTime is the schema descriptor for create_time field.
	modelproviderDescCreateTime := modelproviderMixinFields0[0].Descriptor()
	// modelprovider.DefaultCreateTime holds the default value on creation for the create_time field.
	modelprovider.DefaultCreateTime = modelproviderDescCreateTime.Default.(func() time.Time)
	// modelproviderDescUpdateTime is the schema descriptor for update_time field.
	modelproviderDescUpdateTime := modelproviderMixinFields0[1].Descriptor()
	// modelprovider.DefaultUpdateTime holds the default value on creation for the update_time field.
	modelprovider.DefaultUpdateTime = modelproviderDescUpdateTime.Default.(func() time.Time)
	// modelprovider.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	modelprovider.UpdateDefaultUpdateTime = modelproviderDescUpdateTime.UpdateDefault.(func() time.Time)
	// modelproviderDescName is the schema descriptor for name field.
	modelproviderDescName := modelproviderFields[1].Descriptor()
	// modelprovider.NameValidator is a validator for the "name" field. It is called by the builders before save.
	modelprovider.NameValidator = modelproviderDescName.Validators[0].(func(string) error)
	// modelproviderDescSecret is the schema descriptor for secret field.
	modelproviderDescSecret := modelproviderFields[4].Descriptor()
	// modelprovider.SecretValidator is a validator for the "secret" field. It is called by the builders before save.
	modelprovider.SecretValidator = modelproviderDescSecret.Validators[0].(func([]byte) error)
	// modelproviderDescEnabled is the schema descriptor for enabled field.
	modelproviderDescEnabled := modelproviderFields[5].Descriptor()
	// modelprovider.DefaultEnabled holds the default value on creation for the enabled field.
	modelprovider.DefaultEnabled = modelproviderDescEnabled.Default.(bool)
	// modelproviderDescID is the schema descriptor for id field.
	modelproviderDescID := modelproviderFields[0].Descriptor()
	// modelprovider.DefaultID holds the default value on creation for the id field.
	modelprovider.DefaultID = modelproviderDescID.Default.(func() uuid.UUID)
	taskMixin := schema.Task{}.Mixin()
	taskMixinFields0 := taskMixin[0].Fields()
	_ = taskMixinFields0
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreateTime is the schema descriptor for create_time field.
	taskDescCreateTime := taskMixinFields0[0].Descriptor()
	// task.DefaultCreateTime holds the default value on creation for the create_time field.
	task.DefaultCreateTime = taskDescCreateTime.Default.(func() time.Time)
	// taskDescUpdateTime is the schema descriptor for update_time field.
	taskDescUpdateTime := taskMixinFields0[1].Descriptor()
	// task.DefaultUpdateTime holds the default value on creation for the update_time field.
	task.DefaultUpdateTime = taskDescUpdateTime.Default.(func() time.Time)
	// task.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	task.UpdateDefaultUpdateTime = taskDescUpdateTime.UpdateDefault.(func() time.Time)
	// taskDescTurns is the schema descriptor for turns field.
	taskDescTurns := taskFields[7].Descriptor()
	// task.DefaultTurns holds the default value on creation for the turns field.
	task.DefaultTurns = taskDescTurns.Default.(int64)
	// taskDescToolUses is the schema descriptor for tool_uses field.
	taskDescToolUses := taskFields[8].Descriptor()
	// task.DefaultToolUses holds the default value on creation for the tool_uses field.
	task.DefaultToolUses = taskDescToolUses.Default.(map[string]int64)
	// taskDescID is the schema descriptor for id field.
	taskDescID := taskFields[0].Descriptor()
	// task.DefaultID holds the default value on creation for the id field.
	task.DefaultID = taskDescID.Default.(func() uuid.UUID)
	tasksummaryMixin := schema.TaskSummary{}.Mixin()
	tasksummaryMixinFields0 := tasksummaryMixin[0].Fields()
	_ = tasksummaryMixinFields0
	tasksummaryFields := schema.TaskSummary{}.Fields()
	_ = tasksummaryFields
	// tasksummaryDescCreateTime is the schema descriptor for create_time field.
	tasksummaryDescCreateTime := tasksummaryMixinFields0[0].Descriptor()
	// tasksummary.DefaultCreateTime holds the default value on creation for the create_time field.
	tasksummary.DefaultCreateTime = tasksummaryDescCreateTime.Default.(func() time.Time)
	// tasksummaryDescUpdateTime is the schema descriptor for update_time field.
	tasksummaryDescUpdateTime := tasksummaryMixinFields0[1].Descriptor()
	// tasksummary.DefaultUpdateTime holds the default value on creation for the update_time field.
	tasksummary.DefaultUpdateTime = tasksummaryDescUpdateTime.Default.(func() time.Time)
	// tasksummary.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	tasksummary.UpdateDefaultUpdateTime = tasksummaryDescUpdateTime.UpdateDefault.(func() time.Time)
	// tasksummaryDescTokenBudget is the schema descriptor for token_budget field.
	tasksummaryDescTokenBudget := tasksummaryFields[3].Descriptor()
	// tasksummary.DefaultTokenBudget holds the default value on creation for the token_budget field.
	tasksummary.DefaultTokenBudget = tasksummaryDescTokenBudget.Default.(int64)
	// tasksummaryDescID is the schema descriptor for id field.
	tasksummaryDescID := tasksummaryFields[0].Descriptor()
	// tasksummary.DefaultID holds the default value on creation for the id field.
	tasksummary.DefaultID = tasksummaryDescID.Default.(func() uuid.UUID)
	tokenMixin := schema.Token{}.Mixin()
	tokenMixinFields0 := tokenMixin[0].Fields()
	_ = tokenMixinFields0
	tokenFields := schema.Token{}.Fields()
	_ = tokenFields
	// tokenDescCreateTime is the schema descriptor for create_time field.
	tokenDescCreateTime := tokenMixinFields0[0].Descriptor()
	// token.DefaultCreateTime holds the default value on creation for the create_time field.
	token.DefaultCreateTime = tokenDescCreateTime.Default.(func() time.Time)
	// tokenDescUpdateTime is the schema descriptor for update_time field.
	tokenDescUpdateTime := tokenMixinFields0[1].Descriptor()
	// token.DefaultUpdateTime holds the default value on creation for the update_time field.
	token.DefaultUpdateTime = tokenDescUpdateTime.Default.(func() time.Time)
	// token.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	token.UpdateDefaultUpdateTime = tokenDescUpdateTime.UpdateDefault.(func() time.Time)
	// tokenDescName is the schema descriptor for name field.
	tokenDescName := tokenFields[1].Descriptor()
	// token.NameValidator is a validator for the "name" field. It is called by the builders before save.
	token.NameValidator = tokenDescName.Validators[0].(func(string) error)
	// tokenDescID is the schema descriptor for id field.
	tokenDescID := tokenFields[0].Descriptor()
	// token.DefaultID holds the default value on creation for the id field.
	token.DefaultID = tokenDescID.Default.(func() uuid.UUID)
}
