// Code generated by ent. DO NOT EDIT.

package memory

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/furisto/construct/backend/memory/predicate"
	"github.com/furisto/construct/backend/memory/tasksummary"
)

// TaskSummaryDelete is the builder for deleting a TaskSummary entity.
type TaskSummaryDelete struct {
	config
	hooks    []Hook
	mutation *TaskSummaryMutation
}

// Where appends a list predicates to the TaskSummaryDelete builder.
func (tsd *TaskSummaryDelete) Where(ps ...predicate.TaskSummary) *TaskSummaryDelete {
	tsd.mutation.Where(ps...)
	return tsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tsd *TaskSummaryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tsd.sqlExec, tsd.mutation, tsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tsd *TaskSummaryDelete) ExecX(ctx context.Context) int {
	n, err := tsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tsd *TaskSummaryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tasksummary.Table, sqlgraph.NewFieldSpec(tasksummary.FieldID, field.TypeUUID))
	if ps := tsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tsd.mutation.done = true
	return affected, err
}

// TaskSummaryDeleteOne is the builder for deleting a single TaskSummary entity.
type TaskSummaryDeleteOne struct {
	tsd *TaskSummaryDelete
}

// Where appends a list predicates to the TaskSummaryDelete builder.
func (tsdo *TaskSummaryDeleteOne) Where(ps ...predicate.TaskSummary) *TaskSummaryDeleteOne {
	tsdo.tsd.mutation.Where(ps...)
	return tsdo
}

// Exec executes the deletion query.
func (tsdo *TaskSummaryDeleteOne) Exec(ctx context.Context) error {
	n, err := tsdo.tsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tasksummary.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tsdo *TaskSummaryDeleteOne) ExecX(ctx context.Context) {
	if err := tsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
