// Code generated by ent. DO NOT EDIT.

package memory

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/furisto/construct/backend/memory/message"
	"github.com/furisto/construct/backend/memory/predicate"
	"github.com/furisto/construct/backend/memory/task"
	"github.com/furisto/construct/backend/memory/tasksummary"
	"github.com/google/uuid"
)

// TaskSummaryQuery is the builder for querying TaskSummary entities.
type TaskSummaryQuery struct {
	config
	ctx         *QueryContext
	order       []tasksummary.OrderOption
	inters      []Interceptor
	predicates  []predicate.TaskSummary
	withTask    *TaskQuery
	withMessage *MessageQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TaskSummaryQuery builder.
func (tsq *TaskSummaryQuery) Where(ps ...predicate.TaskSummary) *TaskSummaryQuery {
	tsq.predicates = append(tsq.predicates, ps...)
	return tsq
}

// Limit the number of records to be returned by this query.
func (tsq *TaskSummaryQuery) Limit(limit int) *TaskSummaryQuery {
	tsq.ctx.Limit = &limit
	return tsq
}

// Offset to start from.
func (tsq *TaskSummaryQuery) Offset(offset int) *TaskSummaryQuery {
	tsq.ctx.Offset = &offset
	return tsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tsq *TaskSummaryQuery) Unique(unique bool) *TaskSummaryQuery {
	tsq.ctx.Unique = &unique
	return tsq
}

// Order specifies how the records should be ordered.
func (tsq *TaskSummaryQuery) Order(o ...tasksummary.OrderOption) *TaskSummaryQuery {
	tsq.order = append(tsq.order, o...)
	return tsq
}

// QueryTask chains the current query on the "task" edge.
func (tsq *TaskSummaryQuery) QueryTask() *TaskQuery {
	query := (&TaskClient{config: tsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tasksummary.Table, tasksummary.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, tasksummary.TaskTable, tasksummary.TaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(tsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMessage chains the current query on the "message" edge.
func (tsq *TaskSummaryQuery) QueryMessage() *MessageQuery {
	query := (&MessageClient{config: tsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tasksummary.Table, tasksummary.FieldID, selector),
			sqlgraph.To(message.Table, message.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, tasksummary.MessageTable, tasksummary.MessageColumn),
		)
		fromU = sqlgraph.SetNeighbors(tsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TaskSummary entity from the query.
// Returns a *NotFoundError when no TaskSummary was found.
func (tsq *TaskSummaryQuery) First(ctx context.Context) (*TaskSummary, error) {
	nodes, err := tsq.Limit(1).All(setContextOp(ctx, tsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tasksummary.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tsq *TaskSummaryQuery) FirstX(ctx context.Context) *TaskSummary {
	node, err := tsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TaskSummary ID from the query.
// Returns a *NotFoundError when no TaskSummary ID was found.
func (tsq *TaskSummaryQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tsq.Limit(1).IDs(setContextOp(ctx, tsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tasksummary.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tsq *TaskSummaryQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TaskSummary entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TaskSummary entity is found.
// Returns a *NotFoundError when no TaskSummary entities are found.
func (tsq *TaskSummaryQuery) Only(ctx context.Context) (*TaskSummary, error) {
	nodes, err := tsq.Limit(2).All(setContextOp(ctx, tsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tasksummary.Label}
	default:
		return nil, &NotSingularError{tasksummary.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tsq *TaskSummaryQuery) OnlyX(ctx context.Context) *TaskSummary {
	node, err := tsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TaskSummary ID in the query.
// Returns a *NotSingularError when more than one TaskSummary ID is found.
// Returns a *NotFoundError when no entities are found.
func (tsq *TaskSummaryQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tsq.Limit(2).IDs(setContextOp(ctx, tsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tasksummary.Label}
	default:
		err = &NotSingularError{tasksummary.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tsq *TaskSummaryQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TaskSummaries.
func (tsq *TaskSummaryQuery) All(ctx context.Context) ([]*TaskSummary, error) {
	ctx = setContextOp(ctx, tsq.ctx, ent.OpQueryAll)
	if err := tsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TaskSummary, *TaskSummaryQuery]()
	return withInterceptors[[]*TaskSummary](ctx, tsq, qr, tsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tsq *TaskSummaryQuery) AllX(ctx context.Context) []*TaskSummary {
	nodes, err := tsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TaskSummary IDs.
func (tsq *TaskSummaryQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tsq.ctx.Unique == nil && tsq.path != nil {
		tsq.Unique(true)
	}
	ctx = setContextOp(ctx, tsq.ctx, ent.OpQueryIDs)
	if err = tsq.Select(tasksummary.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tsq *TaskSummaryQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tsq *TaskSummaryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tsq.ctx, ent.OpQueryCount)
	if err := tsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tsq, querierCount[*TaskSummaryQuery](), tsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tsq *TaskSummaryQuery) CountX(ctx context.Context) int {
	count, err := tsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tsq *TaskSummaryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tsq.ctx, ent.OpQueryExist)
	switch _, err := tsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("memory: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tsq *TaskSummaryQuery) ExistX(ctx context.Context) bool {
	exist, err := tsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TaskSummaryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tsq *TaskSummaryQuery) Clone() *TaskSummaryQuery {
	if tsq == nil {
		return nil
	}
	return &TaskSummaryQuery{
		config:      tsq.config,
		ctx:         tsq.ctx.Clone(),
		order:       append([]tasksummary.OrderOption{}, tsq.order...),
		inters:      append([]Interceptor{}, tsq.inters...),
		predicates:  append([]predicate.TaskSummary{}, tsq.predicates...),
		withTask:    tsq.withTask.Clone(),
		withMessage: tsq.withMessage.Clone(),
		// clone intermediate query.
		sql:       tsq.sql.Clone(),
		path:      tsq.path,
		modifiers: append([]func(*sql.Selector){}, tsq.modifiers...),
	}
}

// WithTask tells the query-builder to eager-load the nodes that are connected to
// the "task" edge. The optional arguments are used to configure the query builder of the edge.
func (tsq *TaskSummaryQuery) WithTask(opts ...func(*TaskQuery)) *TaskSummaryQuery {
	query := (&TaskClient{config: tsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tsq.withTask = query
	return tsq
}

// WithMessage tells the query-builder to eager-load the nodes that are connected to
// the "message" edge. The optional arguments are used to configure the query builder of the edge.
func (tsq *TaskSummaryQuery) WithMessage(opts ...func(*MessageQuery)) *TaskSummaryQuery {
	query := (&MessageClient{config: tsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tsq.withMessage = query
	return tsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TaskSummary.Query().
//		GroupBy(tasksummary.FieldCreateTime).
//		Aggregate(memory.Count()).
//		Scan(ctx, &v)
func (tsq *TaskSummaryQuery) GroupBy(field string, fields ...string) *TaskSummaryGroupBy {
	tsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TaskSummaryGroupBy{build: tsq}
	grbuild.flds = &tsq.ctx.Fields
	grbuild.label = tasksummary.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.TaskSummary.Query().
//		Select(tasksummary.FieldCreateTime).
//		Scan(ctx, &v)
func (tsq *TaskSummaryQuery) Select(fields ...string) *TaskSummarySelect {
	tsq.ctx.Fields = append(tsq.ctx.Fields, fields...)
	sbuild := &TaskSummarySelect{TaskSummaryQuery: tsq}
	sbuild.label = tasksummary.Label
	sbuild.flds, sbuild.scan = &tsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TaskSummarySelect configured with the given aggregations.
func (tsq *TaskSummaryQuery) Aggregate(fns ...AggregateFunc) *TaskSummarySelect {
	return tsq.Select().Aggregate(fns...)
}

func (tsq *TaskSummaryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tsq.inters {
		if inter == nil {
			return fmt.Errorf("memory: uninitialized interceptor (forgotten import memory/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tsq); err != nil {
				return err
			}
		}
	}
	for _, f := range tsq.ctx.Fields {
		if !tasksummary.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("memory: invalid field %q for query", f)}
		}
	}
	if tsq.path != nil {
		prev, err := tsq.path(ctx)
		if err != nil {
			return err
		}
		tsq.sql = prev
	}
	return nil
}

func (tsq *TaskSummaryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TaskSummary, error) {
	var (
		nodes       = []*TaskSummary{}
		_spec       = tsq.querySpec()
		loadedTypes = [2]bool{
			tsq.withTask != nil,
			tsq.withMessage != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TaskSummary).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TaskSummary{config: tsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(tsq.modifiers) > 0 {
		_spec.Modifiers = tsq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tsq.withTask; query != nil {
		if err := tsq.loadTask(ctx, query, nodes, nil,
			func(n *TaskSummary, e *Task) { n.Edges.Task = e }); err != nil {
			return nil, err
		}
	}
	if query := tsq.withMessage; query != nil {
		if err := tsq.loadMessage(ctx, query, nodes, nil,
			func(n *TaskSummary, e *Message) { n.Edges.Message = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tsq *TaskSummaryQuery) loadTask(ctx context.Context, query *TaskQuery, nodes []*TaskSummary, init func(*TaskSummary), assign func(*TaskSummary, *Task)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TaskSummary)
	for i := range nodes {
		fk := nodes[i].TaskID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(task.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "task_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (tsq *TaskSummaryQuery) loadMessage(ctx context.Context, query *MessageQuery, nodes []*TaskSummary, init func(*TaskSummary), assign func(*TaskSummary, *Message)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TaskSummary)
	for i := range nodes {
		fk := nodes[i].MessageAnchor
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(message.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "message_anchor" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tsq *TaskSummaryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tsq.querySpec()
	if len(tsq.modifiers) > 0 {
		_spec.Modifiers = tsq.modifiers
	}
	_spec.Node.Columns = tsq.ctx.Fields
	if len(tsq.ctx.Fields) > 0 {
		_spec.Unique = tsq.ctx.Unique != nil && *tsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tsq.driver, _spec)
}

func (tsq *TaskSummaryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tasksummary.Table, tasksummary.Columns, sqlgraph.NewFieldSpec(tasksummary.FieldID, field.TypeUUID))
	_spec.From = tsq.sql
	if unique := tsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tsq.path != nil {
		_spec.Unique = true
	}
	if fields := tsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tasksummary.FieldID)
		for i := range fields {
			if fields[i] != tasksummary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tsq.withTask != nil {
			_spec.Node.AddColumnOnce(tasksummary.FieldTaskID)
		}
		if tsq.withMessage != nil {
			_spec.Node.AddColumnOnce(tasksummary.FieldMessageAnchor)
		}
	}
	if ps := tsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tsq *TaskSummaryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tsq.driver.Dialect())
	t1 := builder.Table(tasksummary.Table)
	columns := tsq.ctx.Fields
	if len(columns) == 0 {
		columns = tasksummary.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tsq.sql != nil {
		selector = tsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tsq.ctx.Unique != nil && *tsq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range tsq.modifiers {
		m(selector)
	}
	for _, p := range tsq.predicates {
		p(selector)
	}
	for _, p := range tsq.order {
		p(selector)
	}
	if offset := tsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tsq *TaskSummaryQuery) Modify(modifiers ...func(s *sql.Selector)) *TaskSummarySelect {
	tsq.modifiers = append(tsq.modifiers, modifiers...)
	return tsq.Select()
}

// TaskSummaryGroupBy is the group-by builder for TaskSummary entities.
type TaskSummaryGroupBy struct {
	selector
	build *TaskSummaryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tsgb *TaskSummaryGroupBy) Aggregate(fns ...AggregateFunc) *TaskSummaryGroupBy {
	tsgb.fns = append(tsgb.fns, fns...)
	return tsgb
}

// Scan applies the selector query and scans the result into the given value.
func (tsgb *TaskSummaryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tsgb.build.ctx, ent.OpQueryGroupBy)
	if err := tsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TaskSummaryQuery, *TaskSummaryGroupBy](ctx, tsgb.build, tsgb, tsgb.build.inters, v)
}

func (tsgb *TaskSummaryGroupBy) sqlScan(ctx context.Context, root *TaskSummaryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tsgb.fns))
	for _, fn := range tsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tsgb.flds)+len(tsgb.fns))
		for _, f := range *tsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TaskSummarySelect is the builder for selecting fields of TaskSummary entities.
type TaskSummarySelect struct {
	*TaskSummaryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tss *TaskSummarySelect) Aggregate(fns ...AggregateFunc) *TaskSummarySelect {
	tss.fns = append(tss.fns, fns...)
	return tss
}

// Scan applies the selector query and scans the result into the given value.
func (tss *TaskSummarySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tss.ctx, ent.OpQuerySelect)
	if err := tss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TaskSummaryQuery, *TaskSummarySelect](ctx, tss.TaskSummaryQuery, tss, tss.inters, v)
}

func (tss *TaskSummarySelect) sqlScan(ctx context.Context, root *TaskSummaryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tss.fns))
	for _, fn := range tss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tss *TaskSummarySelect) Modify(modifiers ...func(s *sql.Selector)) *TaskSummarySelect {
	tss.modifiers = append(tss.modifiers, modifiers...)
	return tss
}
