// Code generated by ent. DO NOT EDIT.

package memory

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/furisto/construct/backend/memory/message"
	"github.com/furisto/construct/backend/memory/schema/types"
	"github.com/furisto/construct/backend/memory/task"
	"github.com/furisto/construct/backend/memory/tasksummary"
	"github.com/google/uuid"
)

// TaskSummary is the model entity for the TaskSummary schema.
type TaskSummary struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// MessageAnchor holds the value of the "message_anchor" field.
	MessageAnchor uuid.UUID `json:"message_anchor,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary *types.TaskSummary `json:"summary,omitempty"`
	// TokenBudget holds the value of the "token_budget" field.
	TokenBudget int64 `json:"token_budget,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID uuid.UUID `json:"task_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskSummaryQuery when eager-loading is set.
	Edges        TaskSummaryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TaskSummaryEdges holds the relations/edges for other nodes in the graph.
type TaskSummaryEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// Message holds the value of the message edge.
	Message *Message `json:"message,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskSummaryEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// MessageOrErr returns the Message value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskSummaryEdges) MessageOrErr() (*Message, error) {
	if e.Message != nil {
		return e.Message, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: message.Label}
	}
	return nil, &NotLoadedError{edge: "message"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskSummary) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tasksummary.FieldSummary:
			values[i] = new([]byte)
		case tasksummary.FieldTokenBudget:
			values[i] = new(sql.NullInt64)
		case tasksummary.FieldCreateTime, tasksummary.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case tasksummary.FieldID, tasksummary.FieldMessageAnchor, tasksummary.FieldTaskID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskSummary fields.
func (ts *TaskSummary) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tasksummary.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ts.ID = *value
			}
		case tasksummary.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				ts.CreateTime = value.Time
			}
		case tasksummary.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				ts.UpdateTime = value.Time
			}
		case tasksummary.FieldMessageAnchor:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field message_anchor", values[i])
			} else if value != nil {
				ts.MessageAnchor = *value
			}
		case tasksummary.FieldSummary:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ts.Summary); err != nil {
					return fmt.Errorf("unmarshal field summary: %w", err)
				}
			}
		case tasksummary.FieldTokenBudget:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field token_budget", values[i])
			} else if value.Valid {
				ts.TokenBudget = value.Int64
			}
		case tasksummary.FieldTaskID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value != nil {
				ts.TaskID = *value
			}
		default:
			ts.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TaskSummary.
// This includes values selected through modifiers, order, etc.
func (ts *TaskSummary) Value(name string) (ent.Value, error) {
	return ts.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the TaskSummary entity.
func (ts *TaskSummary) QueryTask() *TaskQuery {
	return NewTaskSummaryClient(ts.config).QueryTask(ts)
}

// QueryMessage queries the "message" edge of the TaskSummary entity.
func (ts *TaskSummary) QueryMessage() *MessageQuery {
	return NewTaskSummaryClient(ts.config).QueryMessage(ts)
}

// Update returns a builder for updating this TaskSummary.
// Note that you need to call TaskSummary.Unwrap() before calling this method if this TaskSummary
// was returned from a transaction, and the transaction was committed or rolled back.
func (ts *TaskSummary) Update() *TaskSummaryUpdateOne {
	return NewTaskSummaryClient(ts.config).UpdateOne(ts)
}

// Unwrap unwraps the TaskSummary entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ts *TaskSummary) Unwrap() *TaskSummary {
	_tx, ok := ts.config.driver.(*txDriver)
	if !ok {
		panic("memory: TaskSummary is not a transactional entity")
	}
	ts.config.driver = _tx.drv
	return ts
}

// String implements the fmt.Stringer.
func (ts *TaskSummary) String() string {
	var builder strings.Builder
	builder.WriteString("TaskSummary(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ts.ID))
	builder.WriteString("create_time=")
	builder.WriteString(ts.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(ts.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("message_anchor=")
	builder.WriteString(fmt.Sprintf("%v", ts.MessageAnchor))
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(fmt.Sprintf("%v", ts.Summary))
	builder.WriteString(", ")
	builder.WriteString("token_budget=")
	builder.WriteString(fmt.Sprintf("%v", ts.TokenBudget))
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", ts.TaskID))
	builder.WriteByte(')')
	return builder.String()
}

// TaskSummaries is a parsable slice of TaskSummary.
type TaskSummaries []*TaskSummary
