// Code generated by ent. DO NOT EDIT.

package memory

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/furisto/construct/backend/memory/message"
	"github.com/furisto/construct/backend/memory/predicate"
	"github.com/furisto/construct/backend/memory/schema/types"
	"github.com/furisto/construct/backend/memory/task"
	"github.com/furisto/construct/backend/memory/tasksummary"
	"github.com/google/uuid"
)

// TaskSummaryUpdate is the builder for updating TaskSummary entities.
type TaskSummaryUpdate struct {
	config
	hooks     []Hook
	mutation  *TaskSummaryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TaskSummaryUpdate builder.
func (tsu *TaskSummaryUpdate) Where(ps ...predicate.TaskSummary) *TaskSummaryUpdate {
	tsu.mutation.Where(ps...)
	return tsu
}

// SetUpdateTime sets the "update_time" field.
func (tsu *TaskSummaryUpdate) SetUpdateTime(t time.Time) *TaskSummaryUpdate {
	tsu.mutation.SetUpdateTime(t)
	return tsu
}

// SetMessageAnchor sets the "message_anchor" field.
func (tsu *TaskSummaryUpdate) SetMessageAnchor(u uuid.UUID) *TaskSummaryUpdate {
	tsu.mutation.SetMessageAnchor(u)
	return tsu
}

// SetNillableMessageAnchor sets the "message_anchor" field if the given value is not nil.
func (tsu *TaskSummaryUpdate) SetNillableMessageAnchor(u *uuid.UUID) *TaskSummaryUpdate {
	if u != nil {
		tsu.SetMessageAnchor(*u)
	}
	return tsu
}

// SetSummary sets the "summary" field.
func (tsu *TaskSummaryUpdate) SetSummary(ts *types.TaskSummary) *TaskSummaryUpdate {
	tsu.mutation.SetSummary(ts)
	return tsu
}

// SetTokenBudget sets the "token_budget" field.
func (tsu *TaskSummaryUpdate) SetTokenBudget(i int64) *TaskSummaryUpdate {
	tsu.mutation.ResetTokenBudget()
	tsu.mutation.SetTokenBudget(i)
	return tsu
}

// SetNillableTokenBudget sets the "token_budget" field if the given value is not nil.
func (tsu *TaskSummaryUpdate) SetNillableTokenBudget(i *int64) *TaskSummaryUpdate {
	if i != nil {
		tsu.SetTokenBudget(*i)
	}
	return tsu
}

// AddTokenBudget adds i to the "token_budget" field.
func (tsu *TaskSummaryUpdate) AddTokenBudget(i int64) *TaskSummaryUpdate {
	tsu.mutation.AddTokenBudget(i)
	return tsu
}

// SetTaskID sets the "task_id" field.
func (tsu *TaskSummaryUpdate) SetTaskID(u uuid.UUID) *TaskSummaryUpdate {
	tsu.mutation.SetTaskID(u)
	return tsu
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (tsu *TaskSummaryUpdate) SetNillableTaskID(u *uuid.UUID) *TaskSummaryUpdate {
	if u != nil {
		tsu.SetTaskID(*u)
	}
	return tsu
}

// SetTask sets the "task" edge to the Task entity.
func (tsu *TaskSummaryUpdate) SetTask(t *Task) *TaskSummaryUpdate {
	return tsu.SetTaskID(t.ID)
}

// SetMessageID sets the "message" edge to the Message entity by ID.
func (tsu *TaskSummaryUpdate) SetMessageID(id uuid.UUID) *TaskSummaryUpdate {
	tsu.mutation.SetMessageID(id)
	return tsu
}

// SetMessage sets the "message" edge to the Message entity.
func (tsu *TaskSummaryUpdate) SetMessage(m *Message) *TaskSummaryUpdate {
	return tsu.SetMessageID(m.ID)
}

// Mutation returns the TaskSummaryMutation object of the builder.
func (tsu *TaskSummaryUpdate) Mutation() *TaskSummaryMutation {
	return tsu.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (tsu *TaskSummaryUpdate) ClearTask() *TaskSummaryUpdate {
	tsu.mutation.ClearTask()
	return tsu
}

// ClearMessage clears the "message" edge to the Message entity.
func (tsu *TaskSummaryUpdate) ClearMessage() *TaskSummaryUpdate {
	tsu.mutation.ClearMessage()
	return tsu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tsu *TaskSummaryUpdate) Save(ctx context.Context) (int, error) {
	tsu.defaults()
	return withHooks(ctx, tsu.sqlSave, tsu.mutation, tsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tsu *TaskSummaryUpdate) SaveX(ctx context.Context) int {
	affected, err := tsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tsu *TaskSummaryUpdate) Exec(ctx context.Context) error {
	_, err := tsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsu *TaskSummaryUpdate) ExecX(ctx context.Context) {
	if err := tsu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tsu *TaskSummaryUpdate) defaults() {
	if _, ok := tsu.mutation.UpdateTime(); !ok {
		v := tasksummary.UpdateDefaultUpdateTime()
		tsu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tsu *TaskSummaryUpdate) check() error {
	if tsu.mutation.TaskCleared() && len(tsu.mutation.TaskIDs()) > 0 {
		return errors.New(`memory: clearing a required unique edge "TaskSummary.task"`)
	}
	if tsu.mutation.MessageCleared() && len(tsu.mutation.MessageIDs()) > 0 {
		return errors.New(`memory: clearing a required unique edge "TaskSummary.message"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tsu *TaskSummaryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TaskSummaryUpdate {
	tsu.modifiers = append(tsu.modifiers, modifiers...)
	return tsu
}

func (tsu *TaskSummaryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tsu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(tasksummary.Table, tasksummary.Columns, sqlgraph.NewFieldSpec(tasksummary.FieldID, field.TypeUUID))
	if ps := tsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tsu.mutation.UpdateTime(); ok {
		_spec.SetField(tasksummary.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := tsu.mutation.Summary(); ok {
		_spec.SetField(tasksummary.FieldSummary, field.TypeJSON, value)
	}
	if value, ok := tsu.mutation.TokenBudget(); ok {
		_spec.SetField(tasksummary.FieldTokenBudget, field.TypeInt64, value)
	}
	if value, ok := tsu.mutation.AddedTokenBudget(); ok {
		_spec.AddField(tasksummary.FieldTokenBudget, field.TypeInt64, value)
	}
	if tsu.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tasksummary.TaskTable,
			Columns: []string{tasksummary.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tsu.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tasksummary.TaskTable,
			Columns: []string{tasksummary.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tsu.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tasksummary.MessageTable,
			Columns: []string{tasksummary.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tsu.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tasksummary.MessageTable,
			Columns: []string{tasksummary.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(tsu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, tsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tasksummary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tsu.mutation.done = true
	return n, nil
}

// TaskSummaryUpdateOne is the builder for updating a single TaskSummary entity.
type TaskSummaryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TaskSummaryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (tsuo *TaskSummaryUpdateOne) SetUpdateTime(t time.Time) *TaskSummaryUpdateOne {
	tsuo.mutation.SetUpdateTime(t)
	return tsuo
}

// SetMessageAnchor sets the "message_anchor" field.
func (tsuo *TaskSummaryUpdateOne) SetMessageAnchor(u uuid.UUID) *TaskSummaryUpdateOne {
	tsuo.mutation.SetMessageAnchor(u)
	return tsuo
}

// SetNillableMessageAnchor sets the "message_anchor" field if the given value is not nil.
func (tsuo *TaskSummaryUpdateOne) SetNillableMessageAnchor(u *uuid.UUID) *TaskSummaryUpdateOne {
	if u != nil {
		tsuo.SetMessageAnchor(*u)
	}
	return tsuo
}

// SetSummary sets the "summary" field.
func (tsuo *TaskSummaryUpdateOne) SetSummary(ts *types.TaskSummary) *TaskSummaryUpdateOne {
	tsuo.mutation.SetSummary(ts)
	return tsuo
}

// SetTokenBudget sets the "token_budget" field.
func (tsuo *TaskSummaryUpdateOne) SetTokenBudget(i int64) *TaskSummaryUpdateOne {
	tsuo.mutation.ResetTokenBudget()
	tsuo.mutation.SetTokenBudget(i)
	return tsuo
}

// SetNillableTokenBudget sets the "token_budget" field if the given value is not nil.
func (tsuo *TaskSummaryUpdateOne) SetNillableTokenBudget(i *int64) *TaskSummaryUpdateOne {
	if i != nil {
		tsuo.SetTokenBudget(*i)
	}
	return tsuo
}

// AddTokenBudget adds i to the "token_budget" field.
func (tsuo *TaskSummaryUpdateOne) AddTokenBudget(i int64) *TaskSummaryUpdateOne {
	tsuo.mutation.AddTokenBudget(i)
	return tsuo
}

// SetTaskID sets the "task_id" field.
func (tsuo *TaskSummaryUpdateOne) SetTaskID(u uuid.UUID) *TaskSummaryUpdateOne {
	tsuo.mutation.SetTaskID(u)
	return tsuo
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (tsuo *TaskSummaryUpdateOne) SetNillableTaskID(u *uuid.UUID) *TaskSummaryUpdateOne {
	if u != nil {
		tsuo.SetTaskID(*u)
	}
	return tsuo
}

// SetTask sets the "task" edge to the Task entity.
func (tsuo *TaskSummaryUpdateOne) SetTask(t *Task) *TaskSummaryUpdateOne {
	return tsuo.SetTaskID(t.ID)
}

// SetMessageID sets the "message" edge to the Message entity by ID.
func (tsuo *TaskSummaryUpdateOne) SetMessageID(id uuid.UUID) *TaskSummaryUpdateOne {
	tsuo.mutation.SetMessageID(id)
	return tsuo
}

// SetMessage sets the "message" edge to the Message entity.
func (tsuo *TaskSummaryUpdateOne) SetMessage(m *Message) *TaskSummaryUpdateOne {
	return tsuo.SetMessageID(m.ID)
}

// Mutation returns the TaskSummaryMutation object of the builder.
func (tsuo *TaskSummaryUpdateOne) Mutation() *TaskSummaryMutation {
	return tsuo.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (tsuo *TaskSummaryUpdateOne) ClearTask() *TaskSummaryUpdateOne {
	tsuo.mutation.ClearTask()
	return tsuo
}

// ClearMessage clears the "message" edge to the Message entity.
func (tsuo *TaskSummaryUpdateOne) ClearMessage() *TaskSummaryUpdateOne {
	tsuo.mutation.ClearMessage()
	return tsuo
}

// Where appends a list predicates to the TaskSummaryUpdate builder.
func (tsuo *TaskSummaryUpdateOne) Where(ps ...predicate.TaskSummary) *TaskSummaryUpdateOne {
	tsuo.mutation.Where(ps...)
	return tsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tsuo *TaskSummaryUpdateOne) Select(field string, fields ...string) *TaskSummaryUpdateOne {
	tsuo.fields = append([]string{field}, fields...)
	return tsuo
}

// Save executes the query and returns the updated TaskSummary entity.
func (tsuo *TaskSummaryUpdateOne) Save(ctx context.Context) (*TaskSummary, error) {
	tsuo.defaults()
	return withHooks(ctx, tsuo.sqlSave, tsuo.mutation, tsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tsuo *TaskSummaryUpdateOne) SaveX(ctx context.Context) *TaskSummary {
	node, err := tsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tsuo *TaskSummaryUpdateOne) Exec(ctx context.Context) error {
	_, err := tsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsuo *TaskSummaryUpdateOne) ExecX(ctx context.Context) {
	if err := tsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tsuo *TaskSummaryUpdateOne) defaults() {
	if _, ok := tsuo.mutation.UpdateTime(); !ok {
		v := tasksummary.UpdateDefaultUpdateTime()
		tsuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tsuo *TaskSummaryUpdateOne) check() error {
	if tsuo.mutation.TaskCleared() && len(tsuo.mutation.TaskIDs()) > 0 {
		return errors.New(`memory: clearing a required unique edge "TaskSummary.task"`)
	}
	if tsuo.mutation.MessageCleared() && len(tsuo.mutation.MessageIDs()) > 0 {
		return errors.New(`memory: clearing a required unique edge "TaskSummary.message"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tsuo *TaskSummaryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TaskSummaryUpdateOne {
	tsuo.modifiers = append(tsuo.modifiers, modifiers...)
	return tsuo
}

func (tsuo *TaskSummaryUpdateOne) sqlSave(ctx context.Context) (_node *TaskSummary, err error) {
	if err := tsuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tasksummary.Table, tasksummary.Columns, sqlgraph.NewFieldSpec(tasksummary.FieldID, field.TypeUUID))
	id, ok := tsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`memory: missing "TaskSummary.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tasksummary.FieldID)
		for _, f := range fields {
			if !tasksummary.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("memory: invalid field %q for query", f)}
			}
			if f != tasksummary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tsuo.mutation.UpdateTime(); ok {
		_spec.SetField(tasksummary.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := tsuo.mutation.Summary(); ok {
		_spec.SetField(tasksummary.FieldSummary, field.TypeJSON, value)
	}
	if value, ok := tsuo.mutation.TokenBudget(); ok {
		_spec.SetField(tasksummary.FieldTokenBudget, field.TypeInt64, value)
	}
	if value, ok := tsuo.mutation.AddedTokenBudget(); ok {
		_spec.AddField(tasksummary.FieldTokenBudget, field.TypeInt64, value)
	}
	if tsuo.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tasksummary.TaskTable,
			Columns: []string{tasksummary.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tsuo.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tasksummary.TaskTable,
			Columns: []string{tasksummary.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tsuo.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tasksummary.MessageTable,
			Columns: []string{tasksummary.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tsuo.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tasksummary.MessageTable,
			Columns: []string{tasksummary.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(tsuo.modifiers...)
	_node = &TaskSummary{config: tsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tasksummary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tsuo.mutation.done = true
	return _node, nil
}
