// Code generated by ent. DO NOT EDIT.

package memory

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/furisto/construct/backend/memory/message"
	"github.com/furisto/construct/backend/memory/schema/types"
	"github.com/furisto/construct/backend/memory/task"
	"github.com/furisto/construct/backend/memory/tasksummary"
	"github.com/google/uuid"
)

// TaskSummaryCreate is the builder for creating a TaskSummary entity.
type TaskSummaryCreate struct {
	config
	mutation *TaskSummaryMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (tsc *TaskSummaryCreate) SetCreateTime(t time.Time) *TaskSummaryCreate {
	tsc.mutation.SetCreateTime(t)
	return tsc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (tsc *TaskSummaryCreate) SetNillableCreateTime(t *time.Time) *TaskSummaryCreate {
	if t != nil {
		tsc.SetCreateTime(*t)
	}
	return tsc
}

// SetUpdateTime sets the "update_time" field.
func (tsc *TaskSummaryCreate) SetUpdateTime(t time.Time) *TaskSummaryCreate {
	tsc.mutation.SetUpdateTime(t)
	return tsc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (tsc *TaskSummaryCreate) SetNillableUpdateTime(t *time.Time) *TaskSummaryCreate {
	if t != nil {
		tsc.SetUpdateTime(*t)
	}
	return tsc
}

// SetMessageAnchor sets the "message_anchor" field.
func (tsc *TaskSummaryCreate) SetMessageAnchor(u uuid.UUID) *TaskSummaryCreate {
	tsc.mutation.SetMessageAnchor(u)
	return tsc
}

// SetSummary sets the "summary" field.
func (tsc *TaskSummaryCreate) SetSummary(ts *types.TaskSummary) *TaskSummaryCreate {
	tsc.mutation.SetSummary(ts)
	return tsc
}

// SetTokenBudget sets the "token_budget" field.
func (tsc *TaskSummaryCreate) SetTokenBudget(i int64) *TaskSummaryCreate {
	tsc.mutation.SetTokenBudget(i)
	return tsc
}

// SetNillableTokenBudget sets the "token_budget" field if the given value is not nil.
func (tsc *TaskSummaryCreate) SetNillableTokenBudget(i *int64) *TaskSummaryCreate {
	if i != nil {
		tsc.SetTokenBudget(*i)
	}
	return tsc
}

// SetTaskID sets the "task_id" field.
func (tsc *TaskSummaryCreate) SetTaskID(u uuid.UUID) *TaskSummaryCreate {
	tsc.mutation.SetTaskID(u)
	return tsc
}

// SetID sets the "id" field.
func (tsc *TaskSummaryCreate) SetID(u uuid.UUID) *TaskSummaryCreate {
	tsc.mutation.SetID(u)
	return tsc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tsc *TaskSummaryCreate) SetNillableID(u *uuid.UUID) *TaskSummaryCreate {
	if u != nil {
		tsc.SetID(*u)
	}
	return tsc
}

// SetTask sets the "task" edge to the Task entity.
func (tsc *TaskSummaryCreate) SetTask(t *Task) *TaskSummaryCreate {
	return tsc.SetTaskID(t.ID)
}

// SetMessageID sets the "message" edge to the Message entity by ID.
func (tsc *TaskSummaryCreate) SetMessageID(id uuid.UUID) *TaskSummaryCreate {
	tsc.mutation.SetMessageID(id)
	return tsc
}

// SetMessage sets the "message" edge to the Message entity.
func (tsc *TaskSummaryCreate) SetMessage(m *Message) *TaskSummaryCreate {
	return tsc.SetMessageID(m.ID)
}

// Mutation returns the TaskSummaryMutation object of the builder.
func (tsc *TaskSummaryCreate) Mutation() *TaskSummaryMutation {
	return tsc.mutation
}

// Save creates the TaskSummary in the database.
func (tsc *TaskSummaryCreate) Save(ctx context.Context) (*TaskSummary, error) {
	tsc.defaults()
	return withHooks(ctx, tsc.sqlSave, tsc.mutation, tsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tsc *TaskSummaryCreate) SaveX(ctx context.Context) *TaskSummary {
	v, err := tsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tsc *TaskSummaryCreate) Exec(ctx context.Context) error {
	_, err := tsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsc *TaskSummaryCreate) ExecX(ctx context.Context) {
	if err := tsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tsc *TaskSummaryCreate) defaults() {
	if _, ok := tsc.mutation.CreateTime(); !ok {
		v := tasksummary.DefaultCreateTime()
		tsc.mutation.SetCreateTime(v)
	}
	if _, ok := tsc.mutation.UpdateTime(); !ok {
		v := tasksummary.DefaultUpdateTime()
		tsc.mutation.SetUpdateTime(v)
	}
	if _, ok := tsc.mutation.TokenBudget(); !ok {
		v := tasksummary.DefaultTokenBudget
		tsc.mutation.SetTokenBudget(v)
	}
	if _, ok := tsc.mutation.ID(); !ok {
		v := tasksummary.DefaultID()
		tsc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tsc *TaskSummaryCreate) check() error {
	if _, ok := tsc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`memory: missing required field "TaskSummary.create_time"`)}
	}
	if _, ok := tsc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`memory: missing required field "TaskSummary.update_time"`)}
	}
	if _, ok := tsc.mutation.MessageAnchor(); !ok {
		return &ValidationError{Name: "message_anchor", err: errors.New(`memory: missing required field "TaskSummary.message_anchor"`)}
	}
	if _, ok := tsc.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`memory: missing required field "TaskSummary.summary"`)}
	}
	if _, ok := tsc.mutation.TokenBudget(); !ok {
		return &ValidationError{Name: "token_budget", err: errors.New(`memory: missing required field "TaskSummary.token_budget"`)}
	}
	if _, ok := tsc.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`memory: missing required field "TaskSummary.task_id"`)}
	}
	if len(tsc.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`memory: missing required edge "TaskSummary.task"`)}
	}
	if len(tsc.mutation.MessageIDs()) == 0 {
		return &ValidationError{Name: "message", err: errors.New(`memory: missing required edge "TaskSummary.message"`)}
	}
	return nil
}

func (tsc *TaskSummaryCreate) sqlSave(ctx context.Context) (*TaskSummary, error) {
	if err := tsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tsc.mutation.id = &_node.ID
	tsc.mutation.done = true
	return _node, nil
}

func (tsc *TaskSummaryCreate) createSpec() (*TaskSummary, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskSummary{config: tsc.config}
		_spec = sqlgraph.NewCreateSpec(tasksummary.Table, sqlgraph.NewFieldSpec(tasksummary.FieldID, field.TypeUUID))
	)
	if id, ok := tsc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tsc.mutation.CreateTime(); ok {
		_spec.SetField(tasksummary.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := tsc.mutation.UpdateTime(); ok {
		_spec.SetField(tasksummary.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := tsc.mutation.Summary(); ok {
		_spec.SetField(tasksummary.FieldSummary, field.TypeJSON, value)
		_node.Summary = value
	}
	if value, ok := tsc.mutation.TokenBudget(); ok {
		_spec.SetField(tasksummary.FieldTokenBudget, field.TypeInt64, value)
		_node.TokenBudget = value
	}
	if nodes := tsc.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tasksummary.TaskTable,
			Columns: []string{tasksummary.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tsc.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tasksummary.MessageTable,
			Columns: []string{tasksummary.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MessageAnchor = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskSummaryCreateBulk is the builder for creating many TaskSummary entities in bulk.
type TaskSummaryCreateBulk struct {
	config
	err      error
	builders []*TaskSummaryCreate
}

// Save creates the TaskSummary entities in the database.
func (tscb *TaskSummaryCreateBulk) Save(ctx context.Context) ([]*TaskSummary, error) {
	if tscb.err != nil {
		return nil, tscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tscb.builders))
	nodes := make([]*TaskSummary, len(tscb.builders))
	mutators := make([]Mutator, len(tscb.builders))
	for i := range tscb.builders {
		func(i int, root context.Context) {
			builder := tscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskSummaryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tscb *TaskSummaryCreateBulk) SaveX(ctx context.Context) []*TaskSummary {
	v, err := tscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tscb *TaskSummaryCreateBulk) Exec(ctx context.Context) error {
	_, err := tscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tscb *TaskSummaryCreateBulk) ExecX(ctx context.Context) {
	if err := tscb.Exec(ctx); err != nil {
		panic(err)
	}
}
