// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: construct/v1/auth.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/furisto/construct/api/go/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "construct.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceCreateTokenProcedure is the fully-qualified name of the AuthService's CreateToken RPC.
	AuthServiceCreateTokenProcedure = "/construct.v1.AuthService/CreateToken"
	// AuthServiceCreateSetupCodeProcedure is the fully-qualified name of the AuthService's
	// CreateSetupCode RPC.
	AuthServiceCreateSetupCodeProcedure = "/construct.v1.AuthService/CreateSetupCode"
	// AuthServiceListTokensProcedure is the fully-qualified name of the AuthService's ListTokens RPC.
	AuthServiceListTokensProcedure = "/construct.v1.AuthService/ListTokens"
	// AuthServiceRevokeTokenProcedure is the fully-qualified name of the AuthService's RevokeToken RPC.
	AuthServiceRevokeTokenProcedure = "/construct.v1.AuthService/RevokeToken"
	// AuthServiceExchangeSetupCodeProcedure is the fully-qualified name of the AuthService's
	// ExchangeSetupCode RPC.
	AuthServiceExchangeSetupCodeProcedure = "/construct.v1.AuthService/ExchangeSetupCode"
)

// AuthServiceClient is a client for the construct.v1.AuthService service.
type AuthServiceClient interface {
	// CreateToken generates a new authentication token.
	//
	// The plaintext token is returned only once in the response and cannot be
	// retrieved again.
	CreateToken(context.Context, *connect.Request[v1.CreateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error)
	// CreateSetupCode generates a short-lived, single-use code that can be
	// exchanged for a token via ExchangeSetupCode.
	//
	// Setup codes are designed for secure token distribution and expire quickly (default 15 minutes).
	CreateSetupCode(context.Context, *connect.Request[v1.CreateSetupCodeRequest]) (*connect.Response[v1.CreateSetupCodeResponse], error)
	// ListTokens returns metadata about all tokens.
	//
	// Token values are never returned, only metadata such as name, creation time,
	// expiration, and last usage.
	ListTokens(context.Context, *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error)
	// RevokeToken invalidates a token by name, preventing further use.
	RevokeToken(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error)
	// ExchangeSetupCode exchanges a setup code for an authentication token.
	//
	// This is the only unauthenticated endpoint in the auth service. It allows
	// clients to obtain credentials using a short-lived setup code generated
	// by an admin via CreateSetupCode.
	//
	// Setup codes are single-use and automatically invalidated after successful
	// exchange or expiration.
	ExchangeSetupCode(context.Context, *connect.Request[v1.ExchangeSetupCodeRequest]) (*connect.Response[v1.ExchangeSetupCodeResponse], error)
}

// NewAuthServiceClient constructs a client for the construct.v1.AuthService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_construct_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		createToken: connect.NewClient[v1.CreateTokenRequest, v1.CreateTokenResponse](
			httpClient,
			baseURL+AuthServiceCreateTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("CreateToken")),
			connect.WithClientOptions(opts...),
		),
		createSetupCode: connect.NewClient[v1.CreateSetupCodeRequest, v1.CreateSetupCodeResponse](
			httpClient,
			baseURL+AuthServiceCreateSetupCodeProcedure,
			connect.WithSchema(authServiceMethods.ByName("CreateSetupCode")),
			connect.WithClientOptions(opts...),
		),
		listTokens: connect.NewClient[v1.ListTokensRequest, v1.ListTokensResponse](
			httpClient,
			baseURL+AuthServiceListTokensProcedure,
			connect.WithSchema(authServiceMethods.ByName("ListTokens")),
			connect.WithClientOptions(opts...),
		),
		revokeToken: connect.NewClient[v1.RevokeTokenRequest, v1.RevokeTokenResponse](
			httpClient,
			baseURL+AuthServiceRevokeTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("RevokeToken")),
			connect.WithClientOptions(opts...),
		),
		exchangeSetupCode: connect.NewClient[v1.ExchangeSetupCodeRequest, v1.ExchangeSetupCodeResponse](
			httpClient,
			baseURL+AuthServiceExchangeSetupCodeProcedure,
			connect.WithSchema(authServiceMethods.ByName("ExchangeSetupCode")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	createToken       *connect.Client[v1.CreateTokenRequest, v1.CreateTokenResponse]
	createSetupCode   *connect.Client[v1.CreateSetupCodeRequest, v1.CreateSetupCodeResponse]
	listTokens        *connect.Client[v1.ListTokensRequest, v1.ListTokensResponse]
	revokeToken       *connect.Client[v1.RevokeTokenRequest, v1.RevokeTokenResponse]
	exchangeSetupCode *connect.Client[v1.ExchangeSetupCodeRequest, v1.ExchangeSetupCodeResponse]
}

// CreateToken calls construct.v1.AuthService.CreateToken.
func (c *authServiceClient) CreateToken(ctx context.Context, req *connect.Request[v1.CreateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error) {
	return c.createToken.CallUnary(ctx, req)
}

// CreateSetupCode calls construct.v1.AuthService.CreateSetupCode.
func (c *authServiceClient) CreateSetupCode(ctx context.Context, req *connect.Request[v1.CreateSetupCodeRequest]) (*connect.Response[v1.CreateSetupCodeResponse], error) {
	return c.createSetupCode.CallUnary(ctx, req)
}

// ListTokens calls construct.v1.AuthService.ListTokens.
func (c *authServiceClient) ListTokens(ctx context.Context, req *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error) {
	return c.listTokens.CallUnary(ctx, req)
}

// RevokeToken calls construct.v1.AuthService.RevokeToken.
func (c *authServiceClient) RevokeToken(ctx context.Context, req *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error) {
	return c.revokeToken.CallUnary(ctx, req)
}

// ExchangeSetupCode calls construct.v1.AuthService.ExchangeSetupCode.
func (c *authServiceClient) ExchangeSetupCode(ctx context.Context, req *connect.Request[v1.ExchangeSetupCodeRequest]) (*connect.Response[v1.ExchangeSetupCodeResponse], error) {
	return c.exchangeSetupCode.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the construct.v1.AuthService service.
type AuthServiceHandler interface {
	// CreateToken generates a new authentication token.
	//
	// The plaintext token is returned only once in the response and cannot be
	// retrieved again.
	CreateToken(context.Context, *connect.Request[v1.CreateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error)
	// CreateSetupCode generates a short-lived, single-use code that can be
	// exchanged for a token via ExchangeSetupCode.
	//
	// Setup codes are designed for secure token distribution and expire quickly (default 15 minutes).
	CreateSetupCode(context.Context, *connect.Request[v1.CreateSetupCodeRequest]) (*connect.Response[v1.CreateSetupCodeResponse], error)
	// ListTokens returns metadata about all tokens.
	//
	// Token values are never returned, only metadata such as name, creation time,
	// expiration, and last usage.
	ListTokens(context.Context, *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error)
	// RevokeToken invalidates a token by name, preventing further use.
	RevokeToken(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error)
	// ExchangeSetupCode exchanges a setup code for an authentication token.
	//
	// This is the only unauthenticated endpoint in the auth service. It allows
	// clients to obtain credentials using a short-lived setup code generated
	// by an admin via CreateSetupCode.
	//
	// Setup codes are single-use and automatically invalidated after successful
	// exchange or expiration.
	ExchangeSetupCode(context.Context, *connect.Request[v1.ExchangeSetupCodeRequest]) (*connect.Response[v1.ExchangeSetupCodeResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_construct_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceCreateTokenHandler := connect.NewUnaryHandler(
		AuthServiceCreateTokenProcedure,
		svc.CreateToken,
		connect.WithSchema(authServiceMethods.ByName("CreateToken")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceCreateSetupCodeHandler := connect.NewUnaryHandler(
		AuthServiceCreateSetupCodeProcedure,
		svc.CreateSetupCode,
		connect.WithSchema(authServiceMethods.ByName("CreateSetupCode")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceListTokensHandler := connect.NewUnaryHandler(
		AuthServiceListTokensProcedure,
		svc.ListTokens,
		connect.WithSchema(authServiceMethods.ByName("ListTokens")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRevokeTokenHandler := connect.NewUnaryHandler(
		AuthServiceRevokeTokenProcedure,
		svc.RevokeToken,
		connect.WithSchema(authServiceMethods.ByName("RevokeToken")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceExchangeSetupCodeHandler := connect.NewUnaryHandler(
		AuthServiceExchangeSetupCodeProcedure,
		svc.ExchangeSetupCode,
		connect.WithSchema(authServiceMethods.ByName("ExchangeSetupCode")),
		connect.WithHandlerOptions(opts...),
	)
	return "/construct.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceCreateTokenProcedure:
			authServiceCreateTokenHandler.ServeHTTP(w, r)
		case AuthServiceCreateSetupCodeProcedure:
			authServiceCreateSetupCodeHandler.ServeHTTP(w, r)
		case AuthServiceListTokensProcedure:
			authServiceListTokensHandler.ServeHTTP(w, r)
		case AuthServiceRevokeTokenProcedure:
			authServiceRevokeTokenHandler.ServeHTTP(w, r)
		case AuthServiceExchangeSetupCodeProcedure:
			authServiceExchangeSetupCodeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) CreateToken(context.Context, *connect.Request[v1.CreateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.AuthService.CreateToken is not implemented"))
}

func (UnimplementedAuthServiceHandler) CreateSetupCode(context.Context, *connect.Request[v1.CreateSetupCodeRequest]) (*connect.Response[v1.CreateSetupCodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.AuthService.CreateSetupCode is not implemented"))
}

func (UnimplementedAuthServiceHandler) ListTokens(context.Context, *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.AuthService.ListTokens is not implemented"))
}

func (UnimplementedAuthServiceHandler) RevokeToken(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.AuthService.RevokeToken is not implemented"))
}

func (UnimplementedAuthServiceHandler) ExchangeSetupCode(context.Context, *connect.Request[v1.ExchangeSetupCodeRequest]) (*connect.Response[v1.ExchangeSetupCodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.AuthService.ExchangeSetupCode is not implemented"))
}
