// Skill API provides operations for managing skills within Construct.
// Skills are specialized instructions that extend agent capabilities. They can be
// installed from remote repositories (GitHub, GitLab) or direct URLs.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: construct/v1/skill.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/furisto/construct/api/go/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SkillServiceName is the fully-qualified name of the SkillService service.
	SkillServiceName = "construct.v1.SkillService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SkillServiceInstallSkillProcedure is the fully-qualified name of the SkillService's InstallSkill
	// RPC.
	SkillServiceInstallSkillProcedure = "/construct.v1.SkillService/InstallSkill"
	// SkillServiceListSkillsProcedure is the fully-qualified name of the SkillService's ListSkills RPC.
	SkillServiceListSkillsProcedure = "/construct.v1.SkillService/ListSkills"
	// SkillServiceDeleteSkillProcedure is the fully-qualified name of the SkillService's DeleteSkill
	// RPC.
	SkillServiceDeleteSkillProcedure = "/construct.v1.SkillService/DeleteSkill"
	// SkillServiceUpdateSkillProcedure is the fully-qualified name of the SkillService's UpdateSkill
	// RPC.
	SkillServiceUpdateSkillProcedure = "/construct.v1.SkillService/UpdateSkill"
)

// SkillServiceClient is a client for the construct.v1.SkillService service.
type SkillServiceClient interface {
	// InstallSkill installs skills from a remote source.
	InstallSkill(context.Context, *connect.Request[v1.InstallSkillRequest]) (*connect.Response[v1.InstallSkillResponse], error)
	// ListSkills retrieves all installed skills.
	ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error)
	// DeleteSkill removes an installed skill.
	DeleteSkill(context.Context, *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error)
	// UpdateSkill updates installed skills to their latest versions.
	UpdateSkill(context.Context, *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error)
}

// NewSkillServiceClient constructs a client for the construct.v1.SkillService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSkillServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SkillServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	skillServiceMethods := v1.File_construct_v1_skill_proto.Services().ByName("SkillService").Methods()
	return &skillServiceClient{
		installSkill: connect.NewClient[v1.InstallSkillRequest, v1.InstallSkillResponse](
			httpClient,
			baseURL+SkillServiceInstallSkillProcedure,
			connect.WithSchema(skillServiceMethods.ByName("InstallSkill")),
			connect.WithClientOptions(opts...),
		),
		listSkills: connect.NewClient[v1.ListSkillsRequest, v1.ListSkillsResponse](
			httpClient,
			baseURL+SkillServiceListSkillsProcedure,
			connect.WithSchema(skillServiceMethods.ByName("ListSkills")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		deleteSkill: connect.NewClient[v1.DeleteSkillRequest, v1.DeleteSkillResponse](
			httpClient,
			baseURL+SkillServiceDeleteSkillProcedure,
			connect.WithSchema(skillServiceMethods.ByName("DeleteSkill")),
			connect.WithClientOptions(opts...),
		),
		updateSkill: connect.NewClient[v1.UpdateSkillRequest, v1.UpdateSkillResponse](
			httpClient,
			baseURL+SkillServiceUpdateSkillProcedure,
			connect.WithSchema(skillServiceMethods.ByName("UpdateSkill")),
			connect.WithClientOptions(opts...),
		),
	}
}

// skillServiceClient implements SkillServiceClient.
type skillServiceClient struct {
	installSkill *connect.Client[v1.InstallSkillRequest, v1.InstallSkillResponse]
	listSkills   *connect.Client[v1.ListSkillsRequest, v1.ListSkillsResponse]
	deleteSkill  *connect.Client[v1.DeleteSkillRequest, v1.DeleteSkillResponse]
	updateSkill  *connect.Client[v1.UpdateSkillRequest, v1.UpdateSkillResponse]
}

// InstallSkill calls construct.v1.SkillService.InstallSkill.
func (c *skillServiceClient) InstallSkill(ctx context.Context, req *connect.Request[v1.InstallSkillRequest]) (*connect.Response[v1.InstallSkillResponse], error) {
	return c.installSkill.CallUnary(ctx, req)
}

// ListSkills calls construct.v1.SkillService.ListSkills.
func (c *skillServiceClient) ListSkills(ctx context.Context, req *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error) {
	return c.listSkills.CallUnary(ctx, req)
}

// DeleteSkill calls construct.v1.SkillService.DeleteSkill.
func (c *skillServiceClient) DeleteSkill(ctx context.Context, req *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error) {
	return c.deleteSkill.CallUnary(ctx, req)
}

// UpdateSkill calls construct.v1.SkillService.UpdateSkill.
func (c *skillServiceClient) UpdateSkill(ctx context.Context, req *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error) {
	return c.updateSkill.CallUnary(ctx, req)
}

// SkillServiceHandler is an implementation of the construct.v1.SkillService service.
type SkillServiceHandler interface {
	// InstallSkill installs skills from a remote source.
	InstallSkill(context.Context, *connect.Request[v1.InstallSkillRequest]) (*connect.Response[v1.InstallSkillResponse], error)
	// ListSkills retrieves all installed skills.
	ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error)
	// DeleteSkill removes an installed skill.
	DeleteSkill(context.Context, *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error)
	// UpdateSkill updates installed skills to their latest versions.
	UpdateSkill(context.Context, *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error)
}

// NewSkillServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSkillServiceHandler(svc SkillServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	skillServiceMethods := v1.File_construct_v1_skill_proto.Services().ByName("SkillService").Methods()
	skillServiceInstallSkillHandler := connect.NewUnaryHandler(
		SkillServiceInstallSkillProcedure,
		svc.InstallSkill,
		connect.WithSchema(skillServiceMethods.ByName("InstallSkill")),
		connect.WithHandlerOptions(opts...),
	)
	skillServiceListSkillsHandler := connect.NewUnaryHandler(
		SkillServiceListSkillsProcedure,
		svc.ListSkills,
		connect.WithSchema(skillServiceMethods.ByName("ListSkills")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	skillServiceDeleteSkillHandler := connect.NewUnaryHandler(
		SkillServiceDeleteSkillProcedure,
		svc.DeleteSkill,
		connect.WithSchema(skillServiceMethods.ByName("DeleteSkill")),
		connect.WithHandlerOptions(opts...),
	)
	skillServiceUpdateSkillHandler := connect.NewUnaryHandler(
		SkillServiceUpdateSkillProcedure,
		svc.UpdateSkill,
		connect.WithSchema(skillServiceMethods.ByName("UpdateSkill")),
		connect.WithHandlerOptions(opts...),
	)
	return "/construct.v1.SkillService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SkillServiceInstallSkillProcedure:
			skillServiceInstallSkillHandler.ServeHTTP(w, r)
		case SkillServiceListSkillsProcedure:
			skillServiceListSkillsHandler.ServeHTTP(w, r)
		case SkillServiceDeleteSkillProcedure:
			skillServiceDeleteSkillHandler.ServeHTTP(w, r)
		case SkillServiceUpdateSkillProcedure:
			skillServiceUpdateSkillHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSkillServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSkillServiceHandler struct{}

func (UnimplementedSkillServiceHandler) InstallSkill(context.Context, *connect.Request[v1.InstallSkillRequest]) (*connect.Response[v1.InstallSkillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.SkillService.InstallSkill is not implemented"))
}

func (UnimplementedSkillServiceHandler) ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.SkillService.ListSkills is not implemented"))
}

func (UnimplementedSkillServiceHandler) DeleteSkill(context.Context, *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.SkillService.DeleteSkill is not implemented"))
}

func (UnimplementedSkillServiceHandler) UpdateSkill(context.Context, *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.SkillService.UpdateSkill is not implemented"))
}
